import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, ChevronLeft, Lock, Sparkles } from "lucide-react";
import NovaLogo from "../components/NovaLogo";

const OPTIONS = [["Learning level", "High School"], ["Teaching style", "Adaptive"], ["Response length", "Balanced"], ["Hints", "When needed"], ["Examples", "On"], ["Encouragement", "On"]];

export default function DemoSettings() {
    return <main className="min-h-screen bg-[#070a13] text-white"><header className="border-b border-white/[.06] bg-[#070a13]/90"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><Link to="/" className="flex items-center gap-3"><NovaLogo className="h-9 w-9 rounded-xl"/><span className="text-sm font-bold tracking-[.18em]">NOVA</span></Link><Link to="/register" className="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-slate-950">Create account</Link></div></header><section className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-14"><Link to="/" className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white"><ChevronLeft size={15}/>Back</Link><div className="mt-8 flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-cyan-300/15 bg-cyan-300/[.06]"><Sparkles size={21} className="text-cyan-200"/></div><div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-300">Demo preferences</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">Explore how Nova can adapt.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">These are a preview of the controls available in a personal Nova account. Demo preferences are intentionally temporary.</p></div></div><div className="mt-10 overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.025]"><div className="grid sm:grid-cols-2">{OPTIONS.map(([label,value])=><div key={label} className="flex items-center justify-between border-b border-white/[.06] p-5 sm:p-6"><div><div className="text-sm font-medium">{label}</div><div className="mt-1 text-xs text-slate-600">Preview only</div></div><div className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-slate-300">{value}</div></div>)}</div></div><div className="mt-6 rounded-3xl border border-cyan-300/10 bg-cyan-300/[.035] p-6 sm:p-8"><div className="flex gap-4"><Lock className="mt-1 shrink-0 text-cyan-300" size={19}/><div><h2 className="text-lg font-semibold">Want Nova to remember your choices?</h2><p className="mt-2 text-sm leading-6 text-slate-500">Create a free account to unlock saved settings, learning memory, progress and your conversation history.</p><Link to="/register" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-bold text-slate-950">Create free account <ArrowRight size={14}/></Link></div></div></div><div className="mt-10 flex items-center justify-center gap-2 text-xs text-slate-600"><BookOpen size={14}/>Demo mode never touches your personal learning profile.</div></section></main>;
}
