export const NOVA_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", rtl: false }, { code: "es", name: "Spanish", nativeName: "Español", rtl: false }, { code: "zh", name: "Chinese", nativeName: "中文", rtl: false }, { code: "hi", name: "Hindi", nativeName: "हिन्दी", rtl: false }, { code: "fr", name: "French", nativeName: "Français", rtl: false }, { code: "ar", name: "Arabic", nativeName: "العربية", rtl: true }, { code: "pt", name: "Portuguese", nativeName: "Português", rtl: false }, { code: "ru", name: "Russian", nativeName: "Русский", rtl: false }, { code: "de", name: "German", nativeName: "Deutsch", rtl: false }, { code: "ja", name: "Japanese", nativeName: "日本語", rtl: false }, { code: "ko", name: "Korean", nativeName: "한국어", rtl: false }, { code: "it", name: "Italian", nativeName: "Italiano", rtl: false }, { code: "tr", name: "Turkish", nativeName: "Türkçe", rtl: false }, { code: "nl", name: "Dutch", nativeName: "Nederlands", rtl: false }, { code: "pl", name: "Polish", nativeName: "Polski", rtl: false }, { code: "uk", name: "Ukrainian", nativeName: "Українська", rtl: false }, { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", rtl: false }, { code: "th", name: "Thai", nativeName: "ไทย", rtl: false }, { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", rtl: false }, { code: "sv", name: "Swedish", nativeName: "Svenska", rtl: false }, { code: "el", name: "Greek", nativeName: "Ελληνικά", rtl: false }, { code: "cs", name: "Czech", nativeName: "Čeština", rtl: false }, { code: "ro", name: "Romanian", nativeName: "Română", rtl: false }, { code: "hu", name: "Hungarian", nativeName: "Magyar", rtl: false }
];
const LANGUAGE_KEY = "nova_language";
const SETTINGS_KEY = "nova_settings";
export function normalizeLanguage(value) { const raw = String(value || "English").trim().toLowerCase(); return NOVA_LANGUAGES.find(l => l.code === raw || l.name.toLowerCase() === raw || l.nativeName.toLowerCase() === raw) || NOVA_LANGUAGES[0]; }
export function readNovaLanguage() { try { const direct = localStorage.getItem(LANGUAGE_KEY); if (direct) return normalizeLanguage(direct); const raw = localStorage.getItem(SETTINGS_KEY); if (raw) { const parsed = JSON.parse(raw); return normalizeLanguage(parsed?.settings?.language || parsed?.language); } } catch {} return NOVA_LANGUAGES[0]; }

const UI = {
  en:{Back:"Back",Settings:"Settings",Profile:"Profile",Language:"Language",Save:"Save",Saved:"Saved",Cancel:"Cancel",Reset:"Reset",Search:"Search",Loading:"Loading…",Chat:"Chat",Dashboard:"Dashboard",Progress:"Progress",Analytics:"Analytics",Capabilities:"Capabilities",About:"About Nova",Send:"Send",New:"New chat",Latest:"Jump to latest",Retry:"Retry",Regenerate:"Regenerate",Logout:"Log out",Name:"Name",Level:"Learning level",Teaching:"Teaching style",Difficulty:"Difficulty",Length:"Response length",Tone:"Tone",Custom:"Custom instructions",Welcome:"Welcome to Nova",LearnMore:"Learn more"},
  fr:{Back:"Retour",Settings:"Paramètres",Profile:"Profil",Language:"Langue",Save:"Enregistrer",Saved:"Enregistré",Cancel:"Annuler",Reset:"Réinitialiser",Search:"Rechercher",Loading:"Chargement…",Chat:"Discussion",Dashboard:"Tableau de bord",Progress:"Progression",Analytics:"Analyses",Capabilities:"Fonctionnalités",About:"À propos de Nova",Send:"Envoyer",New:"Nouvelle discussion",Latest:"Aller au dernier message",Retry:"Réessayer",Regenerate:"Régénérer",Logout:"Se déconnecter",Name:"Nom",Level:"Niveau d’apprentissage",Teaching:"Style d’enseignement",Difficulty:"Difficulté",Length:"Longueur des réponses",Tone:"Ton",Custom:"Instructions personnalisées",Welcome:"Bienvenue sur Nova",LearnMore:"En savoir plus"},
  es:{Back:"Atrás",Settings:"Configuración",Profile:"Perfil",Language:"Idioma",Save:"Guardar",Saved:"Guardado",Cancel:"Cancelar",Reset:"Restablecer",Search:"Buscar",Loading:"Cargando…",Chat:"Chat",Dashboard:"Panel",Progress:"Progreso",Analytics:"Análisis",Capabilities:"Funciones",About:"Sobre Nova",Send:"Enviar",New:"Nuevo chat",Latest:"Ir al último mensaje",Retry:"Reintentar",Regenerate:"Regenerar",Logout:"Cerrar sesión",Name:"Nombre",Level:"Nivel de aprendizaje",Teaching:"Estilo de enseñanza",Difficulty:"Dificultad",Length:"Longitud de respuesta",Tone:"Tono",Custom:"Instrucciones personalizadas",Welcome:"Bienvenido a Nova",LearnMore:"Más información"},
  de:{Back:"Zurück",Settings:"Einstellungen",Profile:"Profil",Language:"Sprache",Save:"Speichern",Saved:"Gespeichert",Cancel:"Abbrechen",Reset:"Zurücksetzen",Search:"Suchen",Loading:"Wird geladen…",Chat:"Chat",Dashboard:"Dashboard",Progress:"Fortschritt",Analytics:"Analysen",Capabilities:"Funktionen",About:"Über Nova",Send:"Senden",New:"Neuer Chat",Latest:"Zum neuesten",Retry:"Erneut versuchen",Regenerate:"Neu generieren",Logout:"Abmelden",Name:"Name",Level:"Lernniveau",Teaching:"Lehrstil",Difficulty:"Schwierigkeit",Length:"Antwortlänge",Tone:"Ton",Custom:"Eigene Anweisungen",Welcome:"Willkommen bei Nova",LearnMore:"Mehr erfahren"},
  it:{Back:"Indietro",Settings:"Impostazioni",Profile:"Profilo",Language:"Lingua",Save:"Salva",Saved:"Salvato",Cancel:"Annulla",Reset:"Reimposta",Search:"Cerca",Loading:"Caricamento…",Chat:"Chat",Dashboard:"Dashboard",Progress:"Progressi",Analytics:"Analisi",Capabilities:"Funzionalità",About:"Informazioni su Nova",Send:"Invia",New:"Nuova chat",Latest:"Vai all’ultimo",Retry:"Riprova",Regenerate:"Rigenera",Logout:"Esci",Name:"Nome",Level:"Livello di apprendimento",Teaching:"Stile di insegnamento",Difficulty:"Difficoltà",Length:"Lunghezza risposta",Tone:"Tono",Custom:"Istruzioni personalizzate",Welcome:"Benvenuto in Nova",LearnMore:"Scopri di più"},
  pt:{Back:"Voltar",Settings:"Configurações",Profile:"Perfil",Language:"Idioma",Save:"Salvar",Saved:"Salvo",Cancel:"Cancelar",Reset:"Redefinir",Search:"Pesquisar",Loading:"Carregando…",Chat:"Chat",Dashboard:"Painel",Progress:"Progresso",Analytics:"Análises",Capabilities:"Recursos",About:"Sobre a Nova",Send:"Enviar",New:"Novo chat",Latest:"Ir para o mais recente",Retry:"Tentar novamente",Regenerate:"Regenerar",Logout:"Sair",Name:"Nome",Level:"Nível de aprendizagem",Teaching:"Estilo de ensino",Difficulty:"Dificuldade",Length:"Tamanho da resposta",Tone:"Tom",Custom:"Instruções personalizadas",Welcome:"Bem-vindo à Nova",LearnMore:"Saiba mais"},
  zh:{Back:"返回",Settings:"设置",Profile:"个人资料",Language:"语言",Save:"保存",Saved:"已保存",Cancel:"取消",Reset:"重置",Search:"搜索",Loading:"加载中…",Chat:"聊天",Dashboard:"控制面板",Progress:"进度",Analytics:"分析",Capabilities:"功能",About:"关于 Nova",Send:"发送",New:"新对话",Latest:"跳到最新",Retry:"重试",Regenerate:"重新生成",Logout:"退出登录",Name:"姓名",Level:"学习水平",Teaching:"教学风格",Difficulty:"难度",Length:"回答长度",Tone:"语气",Custom:"自定义指令",Welcome:"欢迎使用 Nova",LearnMore:"了解更多"},
  ja:{Back:"戻る",Settings:"設定",Profile:"プロフィール",Language:"言語",Save:"保存",Saved:"保存しました",Cancel:"キャンセル",Reset:"リセット",Search:"検索",Loading:"読み込み中…",Chat:"チャット",Dashboard:"ダッシュボード",Progress:"進捗",Analytics:"分析",Capabilities:"機能",About:"Novaについて",Send:"送信",New:"新しいチャット",Latest:"最新へ",Retry:"再試行",Regenerate:"再生成",Logout:"ログアウト",Name:"名前",Level:"学習レベル",Teaching:"指導スタイル",Difficulty:"難易度",Length:"回答の長さ",Tone:"トーン",Custom:"カスタム指示",Welcome:"Novaへようこそ",LearnMore:"詳しく見る"},
  ko:{Back:"뒤로",Settings:"설정",Profile:"프로필",Language:"언어",Save:"저장",Saved:"저장됨",Cancel:"취소",Reset:"재설정",Search:"검색",Loading:"로드 중…",Chat:"채팅",Dashboard:"대시보드",Progress:"진행 상황",Analytics:"분석",Capabilities:"기능",About:"Nova 정보",Send:"보내기",New:"새 채팅",Latest:"최신으로 이동",Retry:"다시 시도",Regenerate:"다시 생성",Logout:"로그아웃",Name:"이름",Level:"학습 수준",Teaching:"학습 방식",Difficulty:"난이도",Length:"응답 길이",Tone:"말투",Custom:"사용자 지정 지침",Welcome:"Nova에 오신 것을 환영합니다",LearnMore:"자세히 보기"},
  ar:{Back:"رجوع",Settings:"الإعدادات",Profile:"الملف الشخصي",Language:"اللغة",Save:"حفظ",Saved:"تم الحفظ",Cancel:"إلغاء",Reset:"إعادة تعيين",Search:"بحث",Loading:"جارٍ التحميل…",Chat:"الدردشة",Dashboard:"لوحة التحكم",Progress:"التقدم",Analytics:"التحليلات",Capabilities:"القدرات",About:"حول Nova",Send:"إرسال",New:"محادثة جديدة",Latest:"الانتقال إلى الأحدث",Retry:"إعادة المحاولة",Regenerate:"إعادة الإنشاء",Logout:"تسجيل الخروج",Name:"الاسم",Level:"مستوى التعلم",Teaching:"أسلوب التدريس",Difficulty:"الصعوبة",Length:"طول الإجابة",Tone:"النبرة",Custom:"تعليمات مخصصة",Welcome:"مرحبًا بك في Nova",LearnMore:"معرفة المزيد"}
};
export function uiText(key) { const lang = normalizeLanguage(readNovaLanguage()).code; return UI[lang]?.[key] || UI.en[key] || key; }

const reverse = Object.fromEntries(Object.values(UI).flatMap(dict => Object.entries(dict).map(([k,v]) => [v,k])));
let observerInstalled = false;
function translateDom() {
  if (typeof document === "undefined") return;
  const lang = normalizeLanguage(readNovaLanguage()).code;
  if (lang === "en") return;
  const dict = UI[lang] || UI.en;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    if (!node.nodeValue.trim() || node.parentElement?.closest("script,style,textarea,pre,code")) continue;
    const original = node.nodeValue.trim();
    const key = reverse[original] || original;
    const translated = dict[key];
    if (translated && translated !== original) node.nodeValue = node.nodeValue.replace(original, translated);
  }
  document.querySelectorAll("[title],[aria-label],[placeholder]").forEach(el => {
    for (const attr of ["title","aria-label","placeholder"]) {
      const value = el.getAttribute(attr); if (!value) continue;
      const key = reverse[value] || value; const translated = dict[key]; if (translated) el.setAttribute(attr, translated);
    }
  });
}
function installTranslationObserver() {
  if (observerInstalled || typeof document === "undefined") return;
  observerInstalled = true;
  const start = () => { translateDom(); const observer = new MutationObserver(() => { clearTimeout(window.__novaTranslationTimer); window.__novaTranslationTimer = setTimeout(translateDom, 20); }); observer.observe(document.body, { childList:true, subtree:true, characterData:true }); window.addEventListener("nova-language-changed", translateDom); };
  if (document.body) start(); else window.addEventListener("DOMContentLoaded", start, { once:true });
}
export function applyNovaLanguage(value) { const language = normalizeLanguage(value); try { localStorage.setItem(LANGUAGE_KEY, language.code); } catch {} document.documentElement.lang = language.code; document.documentElement.dir = language.rtl ? "rtl" : "ltr"; document.documentElement.dataset.novaLanguage = language.code; installTranslationObserver(); window.dispatchEvent(new CustomEvent("nova-language-changed", { detail: language })); translateDom(); return language; }
export function initializeNovaLanguage() { installTranslationObserver(); return applyNovaLanguage(readNovaLanguage().code); }
