import { normalizeLanguage, readNovaLanguage } from "./i18n";

const dictionaries = {
  en: { back:"Back", settings:"Settings", profile:"Profile", language:"Language", save:"Save changes", saved:"Saved", cancel:"Cancel", reset:"Reset", search:"Search", loading:"Loading…", chat:"Chat", dashboard:"Dashboard", progress:"Progress", analytics:"Analytics", capabilities:"Capabilities", about:"About Nova", send:"Send", newChat:"New chat", jumpLatest:"Jump to latest", retry:"Retry", regenerate:"Regenerate", logout:"Log out", name:"Name", level:"Learning level", teachingStyle:"Teaching style", difficulty:"Difficulty", responseLength:"Response length", tone:"Tone", customInstructions:"Custom instructions", welcome:"Welcome to Nova", adaptiveTutoring:"Adaptive tutoring", learningMemory:"Learning memory", learnMore:"Learn more" },
  fr: { back:"Retour", settings:"Paramètres", profile:"Profil", language:"Langue", save:"Enregistrer", saved:"Enregistré", cancel:"Annuler", reset:"Réinitialiser", search:"Rechercher", loading:"Chargement…", chat:"Discussion", dashboard:"Tableau de bord", progress:"Progression", analytics:"Analyses", capabilities:"Fonctionnalités", about:"À propos de Nova", send:"Envoyer", newChat:"Nouvelle discussion", jumpLatest:"Aller au dernier message", retry:"Réessayer", regenerate:"Régénérer", logout:"Se déconnecter", name:"Nom", level:"Niveau d’apprentissage", teachingStyle:"Style d’enseignement", difficulty:"Difficulté", responseLength:"Longueur des réponses", tone:"Ton", customInstructions:"Instructions personnalisées", welcome:"Bienvenue sur Nova", adaptiveTutoring:"Tutorat adaptatif", learningMemory:"Mémoire d’apprentissage", learnMore:"En savoir plus" },
  es: { back:"Atrás", settings:"Configuración", profile:"Perfil", language:"Idioma", save:"Guardar cambios", saved:"Guardado", cancel:"Cancelar", reset:"Restablecer", search:"Buscar", loading:"Cargando…", chat:"Chat", dashboard:"Panel", progress:"Progreso", analytics:"Análisis", capabilities:"Funciones", about:"Sobre Nova", send:"Enviar", newChat:"Nuevo chat", jumpLatest:"Ir al último mensaje", retry:"Reintentar", regenerate:"Regenerar", logout:"Cerrar sesión", name:"Nombre", level:"Nivel de aprendizaje", teachingStyle:"Estilo de enseñanza", difficulty:"Dificultad", responseLength:"Longitud de respuesta", tone:"Tono", customInstructions:"Instrucciones personalizadas", welcome:"Bienvenido a Nova", adaptiveTutoring:"Tutoría adaptativa", learningMemory:"Memoria de aprendizaje", learnMore:"Más información" },
  de: { back:"Zurück", settings:"Einstellungen", profile:"Profil", language:"Sprache", save:"Änderungen speichern", saved:"Gespeichert", cancel:"Abbrechen", reset:"Zurücksetzen", search:"Suchen", loading:"Wird geladen…", chat:"Chat", dashboard:"Dashboard", progress:"Fortschritt", analytics:"Analysen", capabilities:"Funktionen", about:"Über Nova", send:"Senden", newChat:"Neuer Chat", jumpLatest:"Zum neuesten", retry:"Erneut versuchen", regenerate:"Neu generieren", logout:"Abmelden", name:"Name", level:"Lernniveau", teachingStyle:"Lehrstil", difficulty:"Schwierigkeit", responseLength:"Antwortlänge", tone:"Ton", customInstructions:"Eigene Anweisungen", welcome:"Willkommen bei Nova", adaptiveTutoring:"Adaptives Lernen", learningMemory:"Lernspeicher", learnMore:"Mehr erfahren" },
  it: { back:"Indietro", settings:"Impostazioni", profile:"Profilo", language:"Lingua", save:"Salva modifiche", saved:"Salvato", cancel:"Annulla", reset:"Reimposta", search:"Cerca", loading:"Caricamento…", chat:"Chat", dashboard:"Dashboard", progress:"Progressi", analytics:"Analisi", capabilities:"Funzionalità", about:"Informazioni su Nova", send:"Invia", newChat:"Nuova chat", jumpLatest:"Vai all’ultimo", retry:"Riprova", regenerate:"Rigenera", logout:"Esci", name:"Nome", level:"Livello di apprendimento", teachingStyle:"Stile di insegnamento", difficulty:"Difficoltà", responseLength:"Lunghezza risposta", tone:"Tono", customInstructions:"Istruzioni personalizzate", welcome:"Benvenuto in Nova", adaptiveTutoring:"Tutoraggio adattivo", learningMemory:"Memoria di apprendimento", learnMore:"Scopri di più" },
  pt: { back:"Voltar", settings:"Configurações", profile:"Perfil", language:"Idioma", save:"Salvar alterações", saved:"Salvo", cancel:"Cancelar", reset:"Redefinir", search:"Pesquisar", loading:"Carregando…", chat:"Chat", dashboard:"Painel", progress:"Progresso", analytics:"Análises", capabilities:"Recursos", about:"Sobre a Nova", send:"Enviar", newChat:"Novo chat", jumpLatest:"Ir para o mais recente", retry:"Tentar novamente", regenerate:"Regenerar", logout:"Sair", name:"Nome", level:"Nível de aprendizagem", teachingStyle:"Estilo de ensino", difficulty:"Dificuldade", responseLength:"Tamanho da resposta", tone:"Tom", customInstructions:"Instruções personalizadas", welcome:"Bem-vindo à Nova", adaptiveTutoring:"Tutoria adaptativa", learningMemory:"Memória de aprendizagem", learnMore:"Saiba mais" },
  zh: { back:"返回", settings:"设置", profile:"个人资料", language:"语言", save:"保存更改", saved:"已保存", cancel:"取消", reset:"重置", search:"搜索", loading:"加载中…", chat:"聊天", dashboard:"控制面板", progress:"进度", analytics:"分析", capabilities:"功能", about:"关于 Nova", send:"发送", newChat:"新对话", jumpLatest:"跳到最新", retry:"重试", regenerate:"重新生成", logout:"退出登录", name:"姓名", level:"学习水平", teachingStyle:"教学风格", difficulty:"难度", responseLength:"回答长度", tone:"语气", customInstructions:"自定义指令", welcome:"欢迎使用 Nova", adaptiveTutoring:"自适应辅导", learningMemory:"学习记忆", learnMore:"了解更多" },
  ja: { back:"戻る", settings:"設定", profile:"プロフィール", language:"言語", save:"変更を保存", saved:"保存しました", cancel:"キャンセル", reset:"リセット", search:"検索", loading:"読み込み中…", chat:"チャット", dashboard:"ダッシュボード", progress:"進捗", analytics:"分析", capabilities:"機能", about:"Novaについて", send:"送信", newChat:"新しいチャット", jumpLatest:"最新へ", retry:"再試行", regenerate:"再生成", logout:"ログアウト", name:"名前", level:"学習レベル", teachingStyle:"指導スタイル", difficulty:"難易度", responseLength:"回答の長さ", tone:"トーン", customInstructions:"カスタム指示", welcome:"Novaへようこそ", adaptiveTutoring:"適応型チュータリング", learningMemory:"学習メモリ", learnMore:"詳しく見る" },
  ko: { back:"뒤로", settings:"설정", profile:"프로필", language:"언어", save:"변경 사항 저장", saved:"저장됨", cancel:"취소", reset:"재설정", search:"검색", loading:"로드 중…", chat:"채팅", dashboard:"대시보드", progress:"진행 상황", analytics:"분석", capabilities:"기능", about:"Nova 정보", send:"보내기", newChat:"새 채팅", jumpLatest:"최신으로 이동", retry:"다시 시도", regenerate:"다시 생성", logout:"로그아웃", name:"이름", level:"학습 수준", teachingStyle:"학습 방식", difficulty:"난이도", responseLength:"응답 길이", tone:"말투", customInstructions:"사용자 지정 지침", welcome:"Nova에 오신 것을 환영합니다", adaptiveTutoring:"적응형 튜터링", learningMemory:"학습 메모리", learnMore:"자세히 보기" },
  ar: { back:"رجوع", settings:"الإعدادات", profile:"الملف الشخصي", language:"اللغة", save:"حفظ التغييرات", saved:"تم الحفظ", cancel:"إلغاء", reset:"إعادة تعيين", search:"بحث", loading:"جارٍ التحميل…", chat:"الدردشة", dashboard:"لوحة التحكم", progress:"التقدم", analytics:"التحليلات", capabilities:"القدرات", about:"حول Nova", send:"إرسال", newChat:"محادثة جديدة", jumpLatest:"الانتقال إلى الأحدث", retry:"إعادة المحاولة", regenerate:"إعادة الإنشاء", logout:"تسجيل الخروج", name:"الاسم", level:"مستوى التعلم", teachingStyle:"أسلوب التدريس", difficulty:"الصعوبة", responseLength:"طول الإجابة", tone:"النبرة", customInstructions:"تعليمات مخصصة", welcome:"مرحبًا بك في Nova", adaptiveTutoring:"التدريس التكيفي", learningMemory:"ذاكرة التعلم", learnMore:"معرفة المزيد" },
};

const fallback = dictionaries.en;
export function t(key) { const lang = normalizeLanguage(readNovaLanguage()).code; return dictionaries[lang]?.[key] || fallback[key] || key; }
export function getUiDictionary() { const lang = normalizeLanguage(readNovaLanguage()).code; return dictionaries[lang] || fallback; }
export function installUiTranslationObserver() {
  const update = () => window.dispatchEvent(new CustomEvent("nova-ui-language-changed", { detail: getUiDictionary() }));
  window.addEventListener("nova-language-changed", update);
  return () => window.removeEventListener("nova-language-changed", update);
}
