import { applyNovaLanguage, normalizeLanguage, readNovaLanguage } from "./i18n.js";

/*
 * Nova's UI is rendered by many React pages. This runtime gives those pages a
 * single translation layer without translating user/assistant message content.
 * Exact phrases win first, then individual UI words are translated as a safe
 * fallback. Product/name tokens such as Nova are intentionally preserved.
 */

const UI = {
  en: {
    Back:"Back", Settings:"Settings", Profile:"Profile", Language:"Language", Save:"Save changes", Saved:"Saved", Cancel:"Cancel", Reset:"Reset", Search:"Search", Loading:"Loading…", Chat:"Chat", Dashboard:"Dashboard", Progress:"Progress", Analytics:"Analytics", Capabilities:"Capabilities", About:"About Nova", Send:"Send", New:"New chat", Latest:"Jump to latest", Retry:"Retry", Regenerate:"Regenerate", Logout:"Log out", Name:"Name", Level:"Learning level", Teaching:"Teaching style", Difficulty:"Difficulty", Length:"Response length", Tone:"Tone", Custom:"Custom instructions", Welcome:"Welcome to Nova", LearnMore:"Learn more", Adaptive:"Adaptive Tutor", Personal:"Personal Tutor", Practice:"Practice Coach", Explain:"Explain", Quiz:"Quiz me", Hint:"Give me a hint", Summarize:"Summarize", Delete:"Delete", Edit:"Edit", Copy:"Copy", Download:"Download", History:"History", Clear:"Clear", Close:"Close", Confirm:"Confirm", Continue:"Continue", Home:"Home", Account:"Account", General:"General", Preferences:"Preferences", Appearance:"Appearance", Theme:"Theme", Notifications:"Notifications", Privacy:"Privacy", Security:"Security", Help:"Help", SignIn:"Sign in", SignUp:"Sign up", Email:"Email", Password:"Password", Username:"Username", WelcomeBack:"Welcome back", CreateAccount:"Create account", NoConversations:"No conversations yet", NewConversation:"New conversation", StartConversation:"Start a conversation", AskNova:"Ask Nova anything…", SaveChanges:"Save changes", Unsaved:"Unsaved changes", DifficultyEasy:"Easy", DifficultyMedium:"Medium", DifficultyHard:"Hard", Short:"Short", Balanced:"Balanced", Detailed:"Detailed", Friendly:"Friendly", Formal:"Formal", Casual:"Casual", Enable:"Enable", Disable:"Disable", Yes:"Yes", No:"No", On:"On", Off:"Off", Optional:"Optional", Required:"Required", Next:"Next", Previous:"Previous", Done:"Done", TryAgain:"Try again", Error:"Error", Success:"Success", Online:"Online", Offline:"Offline", LoadingData:"Loading data…", NoData:"No data available", Overview:"Overview", Statistics:"Statistics", Total:"Total", Today:"Today", Week:"This week", Month:"This month", AllTime:"All time", LanguageDescription:"The language Nova should normally use.", AdaptiveDescription:"Adjusts explanations to your level.", PersonalDescription:"Guided, step-by-step help.", PracticeDescription:"Exercises, hints and feedback." },
  fr: {
    Back:"Retour", Settings:"Paramètres", Profile:"Profil", Language:"Langue", Save:"Enregistrer les modifications", Saved:"Enregistré", Cancel:"Annuler", Reset:"Réinitialiser", Search:"Rechercher", Loading:"Chargement…", Chat:"Discussion", Dashboard:"Tableau de bord", Progress:"Progression", Analytics:"Analyses", Capabilities:"Fonctionnalités", About:"À propos de Nova", Send:"Envoyer", New:"Nouvelle discussion", Latest:"Aller au dernier message", Retry:"Réessayer", Regenerate:"Régénérer", Logout:"Se déconnecter", Name:"Nom", Level:"Niveau d’apprentissage", Teaching:"Style d’enseignement", Difficulty:"Difficulté", Length:"Longueur des réponses", Tone:"Ton", Custom:"Instructions personnalisées", Welcome:"Bienvenue sur Nova", LearnMore:"En savoir plus", Adaptive:"Tuteur adaptatif", Personal:"Tuteur personnel", Practice:"Coach d’entraînement", Explain:"Expliquer", Quiz:"M’interroger", Hint:"Donner un indice", Summarize:"Résumer", Delete:"Supprimer", Edit:"Modifier", Copy:"Copier", Download:"Télécharger", History:"Historique", Clear:"Effacer", Close:"Fermer", Confirm:"Confirmer", Continue:"Continuer", Home:"Accueil", Account:"Compte", General:"Général", Preferences:"Préférences", Appearance:"Apparence", Theme:"Thème", Notifications:"Notifications", Privacy:"Confidentialité", Security:"Sécurité", Help:"Aide", SignIn:"Se connecter", SignUp:"S’inscrire", Email:"E-mail", Password:"Mot de passe", Username:"Nom d’utilisateur", WelcomeBack:"Bon retour", CreateAccount:"Créer un compte", NoConversations:"Aucune conversation pour le moment", NewConversation:"Nouvelle conversation", StartConversation:"Commencer une conversation", AskNova:"Demandez n’importe quoi à Nova…", SaveChanges:"Enregistrer les modifications", Unsaved:"Modifications non enregistrées", DifficultyEasy:"Facile", DifficultyMedium:"Moyen", DifficultyHard:"Difficile", Short:"Court", Balanced:"Équilibré", Detailed:"Détaillé", Friendly:"Amical", Formal:"Formel", Casual:"Décontracté", Enable:"Activer", Disable:"Désactiver", Yes:"Oui", No:"Non", On:"Activé", Off:"Désactivé", Optional:"Facultatif", Required:"Obligatoire", Next:"Suivant", Previous:"Précédent", Done:"Terminé", TryAgain:"Réessayer", Error:"Erreur", Success:"Réussi", Online:"En ligne", Offline:"Hors ligne", LoadingData:"Chargement des données…", NoData:"Aucune donnée disponible", Overview:"Vue d’ensemble", Statistics:"Statistiques", Total:"Total", Today:"Aujourd’hui", Week:"Cette semaine", Month:"Ce mois-ci", AllTime:"Depuis toujours", LanguageDescription:"La langue que Nova doit normalement utiliser.", AdaptiveDescription:"Adapte les explications à votre niveau.", PersonalDescription:"Aide guidée étape par étape.", PracticeDescription:"Exercices, indices et retours." },
  es: {
    Back:"Atrás", Settings:"Configuración", Profile:"Perfil", Language:"Idioma", Save:"Guardar cambios", Saved:"Guardado", Cancel:"Cancelar", Reset:"Restablecer", Search:"Buscar", Loading:"Cargando…", Chat:"Chat", Dashboard:"Panel", Progress:"Progreso", Analytics:"Análisis", Capabilities:"Funciones", About:"Sobre Nova", Send:"Enviar", New:"Nuevo chat", Latest:"Ir al último mensaje", Retry:"Reintentar", Regenerate:"Regenerar", Logout:"Cerrar sesión", Name:"Nombre", Level:"Nivel de aprendizaje", Teaching:"Estilo de enseñanza", Difficulty:"Dificultad", Length:"Longitud de respuesta", Tone:"Tono", Custom:"Instrucciones personalizadas", Welcome:"Bienvenido a Nova", LearnMore:"Más información", Adaptive:"Tutor adaptativo", Personal:"Tutor personal", Practice:"Entrenador de práctica", Explain:"Explicar", Quiz:"Pregúntame", Hint:"Dame una pista", Summarize:"Resumir", Delete:"Eliminar", Edit:"Editar", Copy:"Copiar", Download:"Descargar", History:"Historial", Clear:"Borrar", Close:"Cerrar", Confirm:"Confirmar", Continue:"Continuar", Home:"Inicio", Account:"Cuenta", General:"General", Preferences:"Preferencias", Appearance:"Apariencia", Theme:"Tema", Notifications:"Notificaciones", Privacy:"Privacidad", Security:"Seguridad", Help:"Ayuda", SignIn:"Iniciar sesión", SignUp:"Registrarse", Email:"Correo electrónico", Password:"Contraseña", Username:"Nombre de usuario", WelcomeBack:"Bienvenido de nuevo", CreateAccount:"Crear cuenta", NoConversations:"Aún no hay conversaciones", NewConversation:"Nueva conversación", StartConversation:"Iniciar una conversación", AskNova:"Pregúntale cualquier cosa a Nova…", SaveChanges:"Guardar cambios", Unsaved:"Cambios sin guardar", DifficultyEasy:"Fácil", DifficultyMedium:"Medio", DifficultyHard:"Difícil", Short:"Corto", Balanced:"Equilibrado", Detailed:"Detallado", Friendly:"Amable", Formal:"Formal", Casual:"Informal", Enable:"Activar", Disable:"Desactivar", Yes:"Sí", No:"No", On:"Activado", Off:"Desactivado", Optional:"Opcional", Required:"Obligatorio", Next:"Siguiente", Previous:"Anterior", Done:"Listo", TryAgain:"Intentar de nuevo", Error:"Error", Success:"Correcto", Online:"En línea", Offline:"Sin conexión", LoadingData:"Cargando datos…", NoData:"No hay datos disponibles", Overview:"Resumen", Statistics:"Estadísticas", Total:"Total", Today:"Hoy", Week:"Esta semana", Month:"Este mes", AllTime:"Todo el tiempo", LanguageDescription:"El idioma que Nova debería usar normalmente.", AdaptiveDescription:"Adapta las explicaciones a tu nivel.", PersonalDescription:"Ayuda guiada paso a paso.", PracticeDescription:"Ejercicios, pistas y comentarios." },
  de: {
    Back:"Zurück", Settings:"Einstellungen", Profile:"Profil", Language:"Sprache", Save:"Änderungen speichern", Saved:"Gespeichert", Cancel:"Abbrechen", Reset:"Zurücksetzen", Search:"Suchen", Loading:"Wird geladen…", Chat:"Chat", Dashboard:"Dashboard", Progress:"Fortschritt", Analytics:"Analysen", Capabilities:"Funktionen", About:"Über Nova", Send:"Senden", New:"Neuer Chat", Latest:"Zum neuesten", Retry:"Erneut versuchen", Regenerate:"Neu generieren", Logout:"Abmelden", Name:"Name", Level:"Lernniveau", Teaching:"Lehrstil", Difficulty:"Schwierigkeit", Length:"Antwortlänge", Tone:"Ton", Custom:"Eigene Anweisungen", Welcome:"Willkommen bei Nova", LearnMore:"Mehr erfahren", Adaptive:"Adaptiver Tutor", Personal:"Persönlicher Tutor", Practice:"Übungscoach", Explain:"Erklären", Quiz:"Quiz mich", Hint:"Gib mir einen Hinweis", Summarize:"Zusammenfassen", Delete:"Löschen", Edit:"Bearbeiten", Copy:"Kopieren", Download:"Herunterladen", History:"Verlauf", Clear:"Leeren", Close:"Schließen", Confirm:"Bestätigen", Continue:"Weiter", Home:"Startseite", Account:"Konto", General:"Allgemein", Preferences:"Einstellungen", Appearance:"Darstellung", Theme:"Design", Notifications:"Benachrichtigungen", Privacy:"Datenschutz", Security:"Sicherheit", Help:"Hilfe", SignIn:"Anmelden", SignUp:"Registrieren", Email:"E-Mail", Password:"Passwort", Username:"Benutzername", WelcomeBack:"Willkommen zurück", CreateAccount:"Konto erstellen", NoConversations:"Noch keine Unterhaltungen", NewConversation:"Neue Unterhaltung", StartConversation:"Unterhaltung starten", AskNova:"Frag Nova alles…", SaveChanges:"Änderungen speichern", Unsaved:"Ungespeicherte Änderungen", DifficultyEasy:"Einfach", DifficultyMedium:"Mittel", DifficultyHard:"Schwierig", Short:"Kurz", Balanced:"Ausgewogen", Detailed:"Detailliert", Friendly:"Freundlich", Formal:"Formell", Casual:"Locker", Enable:"Aktivieren", Disable:"Deaktivieren", Yes:"Ja", No:"Nein", On:"Ein", Off:"Aus", Optional:"Optional", Required:"Erforderlich", Next:"Weiter", Previous:"Zurück", Done:"Fertig", TryAgain:"Erneut versuchen", Error:"Fehler", Success:"Erfolgreich", Online:"Online", Offline:"Offline", LoadingData:"Daten werden geladen…", NoData:"Keine Daten verfügbar", Overview:"Übersicht", Statistics:"Statistiken", Total:"Gesamt", Today:"Heute", Week:"Diese Woche", Month:"Diesen Monat", AllTime:"Gesamte Zeit", LanguageDescription:"Die Sprache, die Nova normalerweise verwenden soll.", AdaptiveDescription:"Passt Erklärungen an dein Niveau an.", PersonalDescription:"Geführte Hilfe Schritt für Schritt.", PracticeDescription:"Übungen, Hinweise und Feedback." },
  it: {
    Back:"Indietro", Settings:"Impostazioni", Profile:"Profilo", Language:"Lingua", Save:"Salva modifiche", Saved:"Salvato", Cancel:"Annulla", Reset:"Reimposta", Search:"Cerca", Loading:"Caricamento…", Chat:"Chat", Dashboard:"Dashboard", Progress:"Progressi", Analytics:"Analisi", Capabilities:"Funzionalità", About:"Informazioni su Nova", Send:"Invia", New:"Nuova chat", Latest:"Vai all’ultimo", Retry:"Riprova", Regenerate:"Rigenera", Logout:"Esci", Name:"Nome", Level:"Livello di apprendimento", Teaching:"Stile di insegnamento", Difficulty:"Difficoltà", Length:"Lunghezza risposta", Tone:"Tono", Custom:"Istruzioni personalizzate", Welcome:"Benvenuto in Nova", LearnMore:"Scopri di più", Adaptive:"Tutor adattivo", Personal:"Tutor personale", Practice:"Coach di esercitazione", Explain:"Spiega", Quiz:"Fammi un quiz", Hint:"Dammi un suggerimento", Summarize:"Riassumi", Delete:"Elimina", Edit:"Modifica", Copy:"Copia", Download:"Scarica", History:"Cronologia", Clear:"Cancella", Close:"Chiudi", Confirm:"Conferma", Continue:"Continua", Home:"Home", Account:"Account", General:"Generale", Preferences:"Preferenze", Appearance:"Aspetto", Theme:"Tema", Notifications:"Notifiche", Privacy:"Privacy", Security:"Sicurezza", Help:"Aiuto", SignIn:"Accedi", SignUp:"Registrati", Email:"E-mail", Password:"Password", Username:"Nome utente", WelcomeBack:"Bentornato", CreateAccount:"Crea account", NoConversations:"Nessuna conversazione", NewConversation:"Nuova conversazione", StartConversation:"Inizia una conversazione", AskNova:"Chiedi qualsiasi cosa a Nova…", SaveChanges:"Salva modifiche", Unsaved:"Modifiche non salvate", DifficultyEasy:"Facile", DifficultyMedium:"Media", DifficultyHard:"Difficile", Short:"Breve", Balanced:"Bilanciato", Detailed:"Dettagliato", Friendly:"Amichevole", Formal:"Formale", Casual:"Informale", Enable:"Attiva", Disable:"Disattiva", Yes:"Sì", No:"No", On:"Attivo", Off:"Disattivo", Optional:"Opzionale", Required:"Obbligatorio", Next:"Avanti", Previous:"Indietro", Done:"Fatto", TryAgain:"Riprova", Error:"Errore", Success:"Operazione riuscita", Online:"Online", Offline:"Offline", LoadingData:"Caricamento dati…", NoData:"Nessun dato disponibile", Overview:"Panoramica", Statistics:"Statistiche", Total:"Totale", Today:"Oggi", Week:"Questa settimana", Month:"Questo mese", AllTime:"Sempre", LanguageDescription:"La lingua che Nova dovrebbe usare normalmente.", AdaptiveDescription:"Adatta le spiegazioni al tuo livello.", PersonalDescription:"Aiuto guidato passo dopo passo.", PracticeDescription:"Esercizi, suggerimenti e feedback." },
  pt: {
    Back:"Voltar", Settings:"Configurações", Profile:"Perfil", Language:"Idioma", Save:"Salvar alterações", Saved:"Salvo", Cancel:"Cancelar", Reset:"Redefinir", Search:"Pesquisar", Loading:"Carregando…", Chat:"Chat", Dashboard:"Painel", Progress:"Progresso", Analytics:"Análises", Capabilities:"Recursos", About:"Sobre a Nova", Send:"Enviar", New:"Novo chat", Latest:"Ir para o mais recente", Retry:"Tentar novamente", Regenerate:"Regenerar", Logout:"Sair", Name:"Nome", Level:"Nível de aprendizagem", Teaching:"Estilo de ensino", Difficulty:"Dificuldade", Length:"Tamanho da resposta", Tone:"Tom", Custom:"Instruções personalizadas", Welcome:"Bem-vindo à Nova", LearnMore:"Saiba mais", Adaptive:"Tutor adaptativo", Personal:"Tutor pessoal", Practice:"Coach de prática", Explain:"Explicar", Quiz:"Faça um quiz", Hint:"Dê-me uma dica", Summarize:"Resumir", Delete:"Excluir", Edit:"Editar", Copy:"Copiar", Download:"Baixar", History:"Histórico", Clear:"Limpar", Close:"Fechar", Confirm:"Confirmar", Continue:"Continuar", Home:"Início", Account:"Conta", General:"Geral", Preferences:"Preferências", Appearance:"Aparência", Theme:"Tema", Notifications:"Notificações", Privacy:"Privacidade", Security:"Segurança", Help:"Ajuda", SignIn:"Entrar", SignUp:"Cadastrar", Email:"E-mail", Password:"Senha", Username:"Nome de usuário", WelcomeBack:"Bem-vindo de volta", CreateAccount:"Criar conta", NoConversations:"Ainda não há conversas", NewConversation:"Nova conversa", StartConversation:"Iniciar uma conversa", AskNova:"Pergunte qualquer coisa à Nova…", SaveChanges:"Salvar alterações", Unsaved:"Alterações não salvas", DifficultyEasy:"Fácil", DifficultyMedium:"Médio", DifficultyHard:"Difícil", Short:"Curto", Balanced:"Equilibrado", Detailed:"Detalhado", Friendly:"Amigável", Formal:"Formal", Casual:"Casual", Enable:"Ativar", Disable:"Desativar", Yes:"Sim", No:"Não", On:"Ativado", Off:"Desativado", Optional:"Opcional", Required:"Obrigatório", Next:"Próximo", Previous:"Anterior", Done:"Concluído", TryAgain:"Tentar novamente", Error:"Erro", Success:"Sucesso", Online:"Online", Offline:"Offline", LoadingData:"Carregando dados…", NoData:"Nenhum dado disponível", Overview:"Visão geral", Statistics:"Estatísticas", Total:"Total", Today:"Hoje", Week:"Esta semana", Month:"Este mês", AllTime:"Todo o período", LanguageDescription:"O idioma que a Nova normalmente deve usar.", AdaptiveDescription:"Adapta as explicações ao seu nível.", PersonalDescription:"Ajuda guiada passo a passo.", PracticeDescription:"Exercícios, dicas e feedback." },
  nl: { Back:"Terug", Settings:"Instellingen", Profile:"Profiel", Language:"Taal", Save:"Wijzigingen opslaan", Saved:"Opgeslagen", Cancel:"Annuleren", Reset:"Resetten", Search:"Zoeken", Loading:"Laden…", Chat:"Chat", Dashboard:"Dashboard", Progress:"Voortgang", Analytics:"Analyses", Capabilities:"Functies", About:"Over Nova", Send:"Versturen", New:"Nieuwe chat", Latest:"Naar nieuwste", Retry:"Opnieuw proberen", Regenerate:"Opnieuw genereren", Logout:"Uitloggen", Name:"Naam", Level:"Leerniveau", Teaching:"Onderwijsstijl", Difficulty:"Moeilijkheid", Length:"Antwoordlengte", Tone:"Toon", Custom:"Aangepaste instructies", Welcome:"Welkom bij Nova", LearnMore:"Meer informatie", Adaptive:"Adaptieve tutor", Personal:"Persoonlijke tutor", Practice:"Oefencoach", Explain:"Uitleggen", Quiz:"Quiz mij", Hint:"Geef me een hint", Summarize:"Samenvatten", Delete:"Verwijderen", Edit:"Bewerken", Copy:"Kopiëren", Download:"Downloaden", History:"Geschiedenis", Clear:"Wissen", Close:"Sluiten", Confirm:"Bevestigen", Continue:"Doorgaan", Home:"Home", Account:"Account", General:"Algemeen", Preferences:"Voorkeuren", Appearance:"Weergave", Theme:"Thema", Notifications:"Meldingen", Privacy:"Privacy", Security:"Beveiliging", Help:"Help", SignIn:"Inloggen", SignUp:"Registreren", Email:"E-mail", Password:"Wachtwoord", Username:"Gebruikersnaam", WelcomeBack:"Welkom terug", CreateAccount:"Account maken", NoConversations:"Nog geen gesprekken", NewConversation:"Nieuw gesprek", StartConversation:"Start een gesprek", AskNova:"Vraag Nova alles…", SaveChanges:"Wijzigingen opslaan", Unsaved:"Niet-opgeslagen wijzigingen", DifficultyEasy:"Makkelijk", DifficultyMedium:"Gemiddeld", DifficultyHard:"Moeilijk", Short:"Kort", Balanced:"Gebalanceerd", Detailed:"Gedetailleerd", Friendly:"Vriendelijk", Formal:"Formeel", Casual:"Informeel", Enable:"Inschakelen", Disable:"Uitschakelen", Yes:"Ja", No:"Nee", On:"Aan", Off:"Uit", Optional:"Optioneel", Required:"Verplicht", Next:"Volgende", Previous:"Vorige", Done:"Klaar", TryAgain:"Opnieuw proberen", Error:"Fout", Success:"Gelukt", Online:"Online", Offline:"Offline", LoadingData:"Gegevens laden…", NoData:"Geen gegevens beschikbaar", Overview:"Overzicht", Statistics:"Statistieken", Total:"Totaal", Today:"Vandaag", Week:"Deze week", Month:"Deze maand", AllTime:"Alle tijd", LanguageDescription:"De taal die Nova normaal moet gebruiken.", AdaptiveDescription:"Past uitleg aan je niveau aan.", PersonalDescription:"Begeleide hulp stap voor stap.", PracticeDescription:"Oefeningen, hints en feedback." },
  pl: { Back:"Wstecz", Settings:"Ustawienia", Profile:"Profil", Language:"Język", Save:"Zapisz zmiany", Saved:"Zapisano", Cancel:"Anuluj", Reset:"Resetuj", Search:"Szukaj", Loading:"Ładowanie…", Chat:"Czat", Dashboard:"Panel", Progress:"Postęp", Analytics:"Analizy", Capabilities:"Funkcje", About:"O Nova", Send:"Wyślij", New:"Nowy czat", Latest:"Przejdź do najnowszych", Retry:"Spróbuj ponownie", Regenerate:"Wygeneruj ponownie", Logout:"Wyloguj", Name:"Imię", Level:"Poziom nauki", Teaching:"Styl nauczania", Difficulty:"Trudność", Length:"Długość odpowiedzi", Tone:"Ton", Custom:"Własne instrukcje", Welcome:"Witamy w Nova", LearnMore:"Dowiedz się więcej", Adaptive:"Tutor adaptacyjny", Personal:"Osobisty tutor", Practice:"Trener ćwiczeń", Explain:"Wyjaśnij", Quiz:"Przepytaj mnie", Hint:"Daj wskazówkę", Summarize:"Podsumuj", Delete:"Usuń", Edit:"Edytuj", Copy:"Kopiuj", Download:"Pobierz", History:"Historia", Clear:"Wyczyść", Close:"Zamknij", Confirm:"Potwierdź", Continue:"Kontynuuj", Home:"Strona główna", Account:"Konto", General:"Ogólne", Preferences:"Preferencje", Appearance:"Wygląd", Theme:"Motyw", Notifications:"Powiadomienia", Privacy:"Prywatność", Security:"Bezpieczeństwo", Help:"Pomoc", SignIn:"Zaloguj się", SignUp:"Zarejestruj się", Email:"E-mail", Password:"Hasło", Username:"Nazwa użytkownika", WelcomeBack:"Witaj ponownie", CreateAccount:"Utwórz konto", NoConversations:"Brak rozmów", NewConversation:"Nowa rozmowa", StartConversation:"Rozpocznij rozmowę", AskNova:"Zapytaj Nova o cokolwiek…", SaveChanges:"Zapisz zmiany", Unsaved:"Niezapisane zmiany", DifficultyEasy:"Łatwy", DifficultyMedium:"Średni", DifficultyHard:"Trudny", Short:"Krótki", Balanced:"Zrównoważony", Detailed:"Szczegółowy", Friendly:"Przyjazny", Formal:"Formalny", Casual:"Swobodny", Enable:"Włącz", Disable:"Wyłącz", Yes:"Tak", No:"Nie", On:"Włączone", Off:"Wyłączone", Optional:"Opcjonalne", Required:"Wymagane", Next:"Dalej", Previous:"Wstecz", Done:"Gotowe", TryAgain:"Spróbuj ponownie", Error:"Błąd", Success:"Sukces", Online:"Online", Offline:"Offline", LoadingData:"Ładowanie danych…", NoData:"Brak dostępnych danych", Overview:"Przegląd", Statistics:"Statystyki", Total:"Łącznie", Today:"Dzisiaj", Week:"Ten tydzień", Month:"Ten miesiąc", AllTime:"Cały czas", LanguageDescription:"Język, którego Nova powinna normalnie używać.", AdaptiveDescription:"Dostosowuje wyjaśnienia do Twojego poziomu.", PersonalDescription:"Prowadzona pomoc krok po kroku.", PracticeDescription:"Ćwiczenia, wskazówki i informacje zwrotne." },
  uk: { Back:"Назад", Settings:"Налаштування", Profile:"Профіль", Language:"Мова", Save:"Зберегти зміни", Saved:"Збережено", Cancel:"Скасувати", Reset:"Скинути", Search:"Пошук", Loading:"Завантаження…", Chat:"Чат", Dashboard:"Панель", Progress:"Прогрес", Analytics:"Аналітика", Capabilities:"Можливості", About:"Про Nova", Send:"Надіслати", New:"Новий чат", Latest:"До останнього", Retry:"Повторити", Regenerate:"Створити знову", Logout:"Вийти", Name:"Ім’я", Level:"Рівень навчання", Teaching:"Стиль навчання", Difficulty:"Складність", Length:"Довжина відповіді", Tone:"Тон", Custom:"Власні інструкції", Welcome:"Ласкаво просимо до Nova", LearnMore:"Дізнатися більше", Adaptive:"Адаптивний репетитор", Personal:"Особистий репетитор", Practice:"Тренер практики", Explain:"Пояснити", Quiz:"Опитай мене", Hint:"Дай підказку", Summarize:"Підсумувати", Delete:"Видалити", Edit:"Редагувати", Copy:"Копіювати", Download:"Завантажити", History:"Історія", Clear:"Очистити", Close:"Закрити", Confirm:"Підтвердити", Continue:"Продовжити", Home:"Головна", Account:"Обліковий запис", General:"Загальні", Preferences:"Налаштування", Appearance:"Вигляд", Theme:"Тема", Notifications:"Сповіщення", Privacy:"Конфіденційність", Security:"Безпека", Help:"Допомога", SignIn:"Увійти", SignUp:"Зареєструватися", Email:"Електронна пошта", Password:"Пароль", Username:"Ім’я користувача", WelcomeBack:"З поверненням", CreateAccount:"Створити обліковий запис", NoConversations:"Розмов ще немає", NewConversation:"Нова розмова", StartConversation:"Почати розмову", AskNova:"Запитайте Nova про що завгодно…", SaveChanges:"Зберегти зміни", Unsaved:"Незбережені зміни", DifficultyEasy:"Легко", DifficultyMedium:"Середньо", DifficultyHard:"Складно", Short:"Коротко", Balanced:"Збалансовано", Detailed:"Детально", Friendly:"Дружній", Formal:"Формальний", Casual:"Неформальний", Enable:"Увімкнути", Disable:"Вимкнути", Yes:"Так", No:"Ні", On:"Увімкнено", Off:"Вимкнено", Optional:"Необов’язково", Required:"Обов’язково", Next:"Далі", Previous:"Назад", Done:"Готово", TryAgain:"Спробувати ще раз", Error:"Помилка", Success:"Успішно", Online:"Онлайн", Offline:"Офлайн", LoadingData:"Завантаження даних…", NoData:"Немає доступних даних", Overview:"Огляд", Statistics:"Статистика", Total:"Усього", Today:"Сьогодні", Week:"Цього тижня", Month:"Цього місяця", AllTime:"За весь час", LanguageDescription:"Мова, яку Nova зазвичай має використовувати.", AdaptiveDescription:"Адаптує пояснення до вашого рівня.", PersonalDescription:"Покрокова допомога.", PracticeDescription:"Вправи, підказки та відгуки." },
  ru: { Back:"Назад", Settings:"Настройки", Profile:"Профиль", Language:"Язык", Save:"Сохранить изменения", Saved:"Сохранено", Cancel:"Отмена", Reset:"Сбросить", Search:"Поиск", Loading:"Загрузка…", Chat:"Чат", Dashboard:"Панель управления", Progress:"Прогресс", Analytics:"Аналитика", Capabilities:"Возможности", About:"О Nova", Send:"Отправить", New:"Новый чат", Latest:"К последнему", Retry:"Повторить", Regenerate:"Создать заново", Logout:"Выйти", Name:"Имя", Level:"Уровень обучения", Teaching:"Стиль обучения", Difficulty:"Сложность", Length:"Длина ответа", Tone:"Тон", Custom:"Пользовательские инструкции", Welcome:"Добро пожаловать в Nova", LearnMore:"Подробнее", Adaptive:"Адаптивный репетитор", Personal:"Личный репетитор", Practice:"Тренер практики", Explain:"Объяснить", Quiz:"Проверь меня", Hint:"Дай подсказку", Summarize:"Суммировать", Delete:"Удалить", Edit:"Изменить", Copy:"Копировать", Download:"Скачать", History:"История", Clear:"Очистить", Close:"Закрыть", Confirm:"Подтвердить", Continue:"Продолжить", Home:"Главная", Account:"Аккаунт", General:"Общие", Preferences:"Предпочтения", Appearance:"Внешний вид", Theme:"Тема", Notifications:"Уведомления", Privacy:"Конфиденциальность", Security:"Безопасность", Help:"Помощь", SignIn:"Войти", SignUp:"Зарегистрироваться", Email:"Электронная почта", Password:"Пароль", Username:"Имя пользователя", WelcomeBack:"С возвращением", CreateAccount:"Создать аккаунт", NoConversations:"Пока нет разговоров", NewConversation:"Новый разговор", StartConversation:"Начать разговор", AskNova:"Спросите Nova о чём угодно…", SaveChanges:"Сохранить изменения", Unsaved:"Несохранённые изменения", DifficultyEasy:"Легко", DifficultyMedium:"Средне", DifficultyHard:"Сложно", Short:"Короткий", Balanced:"Сбалансированный", Detailed:"Подробный", Friendly:"Дружелюбный", Formal:"Формальный", Casual:"Неформальный", Enable:"Включить", Disable:"Отключить", Yes:"Да", No:"Нет", On:"Вкл.", Off:"Выкл.", Optional:"Необязательно", Required:"Обязательно", Next:"Далее", Previous:"Назад", Done:"Готово", TryAgain:"Попробовать снова", Error:"Ошибка", Success:"Успешно", Online:"Онлайн", Offline:"Офлайн", LoadingData:"Загрузка данных…", NoData:"Нет доступных данных", Overview:"Обзор", Statistics:"Статистика", Total:"Всего", Today:"Сегодня", Week:"На этой неделе", Month:"В этом месяце", AllTime:"За всё время", LanguageDescription:"Язык, который Nova обычно должна использовать.", AdaptiveDescription:"Адаптирует объяснения к вашему уровню.", PersonalDescription:"Пошаговая помощь.", PracticeDescription:"Упражнения, подсказки и обратная связь." },
  tr: { Back:"Geri", Settings:"Ayarlar", Profile:"Profil", Language:"Dil", Save:"Değişiklikleri kaydet", Saved:"Kaydedildi", Cancel:"İptal", Reset:"Sıfırla", Search:"Ara", Loading:"Yükleniyor…", Chat:"Sohbet", Dashboard:"Kontrol paneli", Progress:"İlerleme", Analytics:"Analiz", Capabilities:"Yetenekler", About:"Nova hakkında", Send:"Gönder", New:"Yeni sohbet", Latest:"Son mesaja git", Retry:"Tekrar dene", Regenerate:"Yeniden oluştur", Logout:"Çıkış yap", Name:"Ad", Level:"Öğrenme seviyesi", Teaching:"Öğretim stili", Difficulty:"Zorluk", Length:"Yanıt uzunluğu", Tone:"Ton", Custom:"Özel talimatlar", Welcome:"Nova'ya hoş geldiniz", LearnMore:"Daha fazla bilgi", Adaptive:"Uyarlanabilir eğitmen", Personal:"Kişisel eğitmen", Practice:"Pratik koçu", Explain:"Açıkla", Quiz:"Beni sınav yap", Hint:"İpucu ver", Summarize:"Özetle", Delete:"Sil", Edit:"Düzenle", Copy:"Kopyala", Download:"İndir", History:"Geçmiş", Clear:"Temizle", Close:"Kapat", Confirm:"Onayla", Continue:"Devam et", Home:"Ana sayfa", Account:"Hesap", General:"Genel", Preferences:"Tercihler", Appearance:"Görünüm", Theme:"Tema", Notifications:"Bildirimler", Privacy:"Gizlilik", Security:"Güvenlik", Help:"Yardım", SignIn:"Giriş yap", SignUp:"Kayıt ol", Email:"E-posta", Password:"Şifre", Username:"Kullanıcı adı", WelcomeBack:"Tekrar hoş geldiniz", CreateAccount:"Hesap oluştur", NoConversations:"Henüz konuşma yok", NewConversation:"Yeni konuşma", StartConversation:"Konuşma başlat", AskNova:"Nova'ya her şeyi sor…", SaveChanges:"Değişiklikleri kaydet", Unsaved:"Kaydedilmemiş değişiklikler", DifficultyEasy:"Kolay", DifficultyMedium:"Orta", DifficultyHard:"Zor", Short:"Kısa", Balanced:"Dengeli", Detailed:"Ayrıntılı", Friendly:"Samimi", Formal:"Resmî", Casual:"Gündelik", Enable:"Etkinleştir", Disable:"Devre dışı bırak", Yes:"Evet", No:"Hayır", On:"Açık", Off:"Kapalı", Optional:"İsteğe bağlı", Required:"Gerekli", Next:"İleri", Previous:"Önceki", Done:"Bitti", TryAgain:"Tekrar dene", Error:"Hata", Success:"Başarılı", Online:"Çevrimiçi", Offline:"Çevrimdışı", LoadingData:"Veriler yükleniyor…", NoData:"Veri yok", Overview:"Genel bakış", Statistics:"İstatistikler", Total:"Toplam", Today:"Bugün", Week:"Bu hafta", Month:"Bu ay", AllTime:"Tüm zamanlar", LanguageDescription:"Nova'nın normalde kullanması gereken dil.", AdaptiveDescription:"Açıklamaları seviyene göre ayarlar.", PersonalDescription:"Adım adım rehberli yardım.", PracticeDescription:"Alıştırmalar, ipuçları ve geri bildirim." },
  sv: { Back:"Tillbaka", Settings:"Inställningar", Profile:"Profil", Language:"Språk", Save:"Spara ändringar", Saved:"Sparat", Cancel:"Avbryt", Reset:"Återställ", Search:"Sök", Loading:"Laddar…", Chat:"Chatt", Dashboard:"Instrumentpanel", Progress:"Framsteg", Analytics:"Analys", Capabilities:"Funktioner", About:"Om Nova", Send:"Skicka", New:"Ny chatt", Latest:"Gå till senaste", Retry:"Försök igen", Regenerate:"Generera igen", Logout:"Logga ut", Name:"Namn", Level:"Inlärningsnivå", Teaching:"Undervisningsstil", Difficulty:"Svårighet", Length:"Svarslängd", Tone:"Ton", Custom:"Egna instruktioner", Welcome:"Välkommen till Nova", LearnMore:"Läs mer", Adaptive:"Adaptiv handledare", Personal:"Personlig handledare", Practice:"Övningscoach", Explain:"Förklara", Quiz:"Förhör mig", Hint:"Ge mig en ledtråd", Summarize:"Sammanfatta", Delete:"Ta bort", Edit:"Redigera", Copy:"Kopiera", Download:"Ladda ner", History:"Historik", Clear:"Rensa", Close:"Stäng", Confirm:"Bekräfta", Continue:"Fortsätt", Home:"Hem", Account:"Konto", General:"Allmänt", Preferences:"Inställningar", Appearance:"Utseende", Theme:"Tema", Notifications:"Aviseringar", Privacy:"Integritet", Security:"Säkerhet", Help:"Hjälp", SignIn:"Logga in", SignUp:"Registrera dig", Email:"E-post", Password:"Lösenord", Username:"Användarnamn", WelcomeBack:"Välkommen tillbaka", CreateAccount:"Skapa konto", NoConversations:"Inga konversationer ännu", NewConversation:"Ny konversation", StartConversation:"Starta en konversation", AskNova:"Fråga Nova vad som helst…", SaveChanges:"Spara ändringar", Unsaved:"Osparade ändringar", DifficultyEasy:"Lätt", DifficultyMedium:"Medel", DifficultyHard:"Svårt", Short:"Kort", Balanced:"Balanserad", Detailed:"Detaljerad", Friendly:"Vänlig", Formal:"Formell", Casual:"Avslappnad", Enable:"Aktivera", Disable:"Inaktivera", Yes:"Ja", No:"Nej", On:"På", Off:"Av", Optional:"Valfritt", Required:"Obligatoriskt", Next:"Nästa", Previous:"Föregående", Done:"Klar", TryAgain:"Försök igen", Error:"Fel", Success:"Lyckades", Online:"Online", Offline:"Offline", LoadingData:"Laddar data…", NoData:"Inga data tillgängliga", Overview:"Översikt", Statistics:"Statistik", Total:"Totalt", Today:"Idag", Week:"Den här veckan", Month:"Den här månaden", AllTime:"Hela tiden", LanguageDescription:"Språket som Nova normalt ska använda.", AdaptiveDescription:"Anpassar förklaringar efter din nivå.", PersonalDescription:"Guidad hjälp steg för steg.", PracticeDescription:"Övningar, ledtrådar och feedback." },
  el: { Back:"Πίσω", Settings:"Ρυθμίσεις", Profile:"Προφίλ", Language:"Γλώσσα", Save:"Αποθήκευση αλλαγών", Saved:"Αποθηκεύτηκε", Cancel:"Ακύρωση", Reset:"Επαναφορά", Search:"Αναζήτηση", Loading:"Φόρτωση…", Chat:"Συνομιλία", Dashboard:"Πίνακας", Progress:"Πρόοδος", Analytics:"Αναλύσεις", Capabilities:"Δυνατότητες", About:"Σχετικά με το Nova", Send:"Αποστολή", New:"Νέα συνομιλία", Latest:"Μετάβαση στο πιο πρόσφατο", Retry:"Δοκιμή ξανά", Regenerate:"Νέα δημιουργία", Logout:"Αποσύνδεση", Name:"Όνομα", Level:"Επίπεδο μάθησης", Teaching:"Στυλ διδασκαλίας", Difficulty:"Δυσκολία", Length:"Μήκος απάντησης", Tone:"Τόνος", Custom:"Προσαρμοσμένες οδηγίες", Welcome:"Καλώς ήρθατε στο Nova", LearnMore:"Μάθετε περισσότερα", Adaptive:"Προσαρμοστικός καθηγητής", Personal:"Προσωπικός καθηγητής", Practice:"Προπονητής εξάσκησης", Explain:"Εξήγηση", Quiz:"Κάνε μου κουίζ", Hint:"Δώσε μου υπόδειξη", Summarize:"Σύνοψη", Delete:"Διαγραφή", Edit:"Επεξεργασία", Copy:"Αντιγραφή", Download:"Λήψη", History:"Ιστορικό", Clear:"Εκκαθάριση", Close:"Κλείσιμο", Confirm:"Επιβεβαίωση", Continue:"Συνέχεια", Home:"Αρχική", Account:"Λογαριασμός", General:"Γενικά", Preferences:"Προτιμήσεις", Appearance:"Εμφάνιση", Theme:"Θέμα", Notifications:"Ειδοποιήσεις", Privacy:"Απόρρητο", Security:"Ασφάλεια", Help:"Βοήθεια", SignIn:"Σύνδεση", SignUp:"Εγγραφή", Email:"Email", Password:"Κωδικός", Username:"Όνομα χρήστη", WelcomeBack:"Καλώς ήρθατε ξανά", CreateAccount:"Δημιουργία λογαριασμού", NoConversations:"Δεν υπάρχουν συνομιλίες", NewConversation:"Νέα συνομιλία", StartConversation:"Έναρξη συνομιλίας", AskNova:"Ρωτήστε το Nova οτιδήποτε…", SaveChanges:"Αποθήκευση αλλαγών", Unsaved:"Μη αποθηκευμένες αλλαγές", DifficultyEasy:"Εύκολο", DifficultyMedium:"Μέτριο", DifficultyHard:"Δύσκολο", Short:"Σύντομο", Balanced:"Ισορροπημένο", Detailed:"Λεπτομερές", Friendly:"Φιλικό", Formal:"Επίσημο", Casual:"Ανεπίσημο", Enable:"Ενεργοποίηση", Disable:"Απενεργοποίηση", Yes:"Ναι", No:"Όχι", On:"Ενεργό", Off:"Ανενεργό", Optional:"Προαιρετικό", Required:"Απαιτείται", Next:"Επόμενο", Previous:"Προηγούμενο", Done:"Ολοκληρώθηκε", TryAgain:"Δοκιμάστε ξανά", Error:"Σφάλμα", Success:"Επιτυχία", Online:"Σε σύνδεση", Offline:"Εκτός σύνδεσης", LoadingData:"Φόρτωση δεδομένων…", NoData:"Δεν υπάρχουν δεδομένα", Overview:"Επισκόπηση", Statistics:"Στατιστικά", Total:"Σύνολο", Today:"Σήμερα", Week:"Αυτή την εβδομάδα", Month:"Αυτόν τον μήνα", AllTime:"Όλο το διάστημα", LanguageDescription:"Η γλώσσα που θα χρησιμοποιεί κανονικά το Nova.", AdaptiveDescription:"Προσαρμόζει τις εξηγήσεις στο επίπεδό σας.", PersonalDescription:"Καθοδηγούμενη βοήθεια βήμα προς βήμα.", PracticeDescription:"Ασκήσεις, υποδείξεις και σχόλια." },
  cs: { Back:"Zpět", Settings:"Nastavení", Profile:"Profil", Language:"Jazyk", Save:"Uložit změny", Saved:"Uloženo", Cancel:"Zrušit", Reset:"Obnovit", Search:"Hledat", Loading:"Načítání…", Chat:"Chat", Dashboard:"Panel", Progress:"Pokrok", Analytics:"Analytika", Capabilities:"Možnosti", About:"O Nova", Send:"Odeslat", New:"Nový chat", Latest:"Přejít na nejnovější", Retry:"Zkusit znovu", Regenerate:"Vygenerovat znovu", Logout:"Odhlásit", Name:"Jméno", Level:"Úroveň učení", Teaching:"Styl výuky", Difficulty:"Obtížnost", Length:"Délka odpovědi", Tone:"Tón", Custom:"Vlastní pokyny", Welcome:"Vítejte v Nova", LearnMore:"Zjistit více", Adaptive:"Adaptivní tutor", Personal:"Osobní tutor", Practice:"Trenér procvičování", Explain:"Vysvětlit", Quiz:"Vyzkoušej mě", Hint:"Dej mi nápovědu", Summarize:"Shrnout", Delete:"Smazat", Edit:"Upravit", Copy:"Kopírovat", Download:"Stáhnout", History:"Historie", Clear:"Vymazat", Close:"Zavřít", Confirm:"Potvrdit", Continue:"Pokračovat", Home:"Domů", Account:"Účet", General:"Obecné", Preferences:"Předvolby", Appearance:"Vzhled", Theme:"Motiv", Notifications:"Oznámení", Privacy:"Soukromí", Security:"Zabezpečení", Help:"Nápověda", SignIn:"Přihlásit se", SignUp:"Registrovat se", Email:"E-mail", Password:"Heslo", Username:"Uživatelské jméno", WelcomeBack:"Vítejte zpět", CreateAccount:"Vytvořit účet", NoConversations:"Zatím žádné konverzace", NewConversation:"Nová konverzace", StartConversation:"Začít konverzaci", AskNova:"Zeptejte se Nova na cokoli…", SaveChanges:"Uložit změny", Unsaved:"Neuložené změny", DifficultyEasy:"Snadná", DifficultyMedium:"Střední", DifficultyHard:"Obtížná", Short:"Krátká", Balanced:"Vyvážená", Detailed:"Podrobná", Friendly:"Přátelský", Formal:"Formální", Casual:"Neformální", Enable:"Povolit", Disable:"Zakázat", Yes:"Ano", No:"Ne", On:"Zapnuto", Off:"Vypnuto", Optional:"Volitelné", Required:"Povinné", Next:"Další", Previous:"Předchozí", Done:"Hotovo", TryAgain:"Zkusit znovu", Error:"Chyba", Success:"Úspěch", Online:"Online", Offline:"Offline", LoadingData:"Načítání dat…", NoData:"Nejsou k dispozici žádná data", Overview:"Přehled", Statistics:"Statistiky", Total:"Celkem", Today:"Dnes", Week:"Tento týden", Month:"Tento měsíc", AllTime:"Celkem", LanguageDescription:"Jazyk, který má Nova běžně používat.", AdaptiveDescription:"Přizpůsobuje vysvětlení vaší úrovni.", PersonalDescription:"Vedená pomoc krok za krokem.", PracticeDescription:"Cvičení, nápovědy a zpětná vazba." },
  ro: { Back:"Înapoi", Settings:"Setări", Profile:"Profil", Language:"Limbă", Save:"Salvează modificările", Saved:"Salvat", Cancel:"Anulează", Reset:"Resetează", Search:"Caută", Loading:"Se încarcă…", Chat:"Chat", Dashboard:"Panou", Progress:"Progres", Analytics:"Analiză", Capabilities:"Funcții", About:"Despre Nova", Send:"Trimite", New:"Chat nou", Latest:"Mergi la ultimul", Retry:"Încearcă din nou", Regenerate:"Regenerează", Logout:"Deconectare", Name:"Nume", Level:"Nivel de învățare", Teaching:"Stil de predare", Difficulty:"Dificultate", Length:"Lungimea răspunsului", Tone:"Ton", Custom:"Instrucțiuni personalizate", Welcome:"Bine ai venit la Nova", LearnMore:"Află mai multe", Adaptive:"Tutor adaptiv", Personal:"Tutor personal", Practice:"Antrenor de practică", Explain:"Explică", Quiz:"Testează-mă", Hint:"Dă-mi un indiciu", Summarize:"Rezumă", Delete:"Șterge", Edit:"Editează", Copy:"Copiază", Download:"Descarcă", History:"Istoric", Clear:"Șterge tot", Close:"Închide", Confirm:"Confirmă", Continue:"Continuă", Home:"Acasă", Account:"Cont", General:"General", Preferences:"Preferințe", Appearance:"Aspect", Theme:"Temă", Notifications:"Notificări", Privacy:"Confidențialitate", Security:"Securitate", Help:"Ajutor", SignIn:"Autentificare", SignUp:"Înregistrare", Email:"E-mail", Password:"Parolă", Username:"Nume de utilizator", WelcomeBack:"Bine ai revenit", CreateAccount:"Creează cont", NoConversations:"Nu există încă conversații", NewConversation:"Conversație nouă", StartConversation:"Începe o conversație", AskNova:"Întreabă Nova orice…", SaveChanges:"Salvează modificările", Unsaved:"Modificări nesalvate", DifficultyEasy:"Ușor", DifficultyMedium:"Mediu", DifficultyHard:"Dificil", Short:"Scurt", Balanced:"Echilibrat", Detailed:"Detaliat", Friendly:"Prietenos", Formal:"Formal", Casual:"Relaxat", Enable:"Activează", Disable:"Dezactivează", Yes:"Da", No:"Nu", On:"Activat", Off:"Dezactivat", Optional:"Opțional", Required:"Obligatoriu", Next:"Următorul", Previous:"Anterior", Done:"Gata", TryAgain:"Încearcă din nou", Error:"Eroare", Success:"Succes", Online:"Online", Offline:"Offline", LoadingData:"Se încarcă datele…", NoData:"Nu există date disponibile", Overview:"Prezentare generală", Statistics:"Statistici", Total:"Total", Today:"Astăzi", Week:"Săptămâna aceasta", Month:"Luna aceasta", AllTime:"Tot timpul", LanguageDescription:"Limba pe care Nova ar trebui să o folosească în mod normal.", AdaptiveDescription:"Adaptează explicațiile la nivelul tău.", PersonalDescription:"Ajutor ghidat pas cu pas.", PracticeDescription:"Exerciții, indicii și feedback." },
  hu: { Back:"Vissza", Settings:"Beállítások", Profile:"Profil", Language:"Nyelv", Save:"Módosítások mentése", Saved:"Mentve", Cancel:"Mégse", Reset:"Visszaállítás", Search:"Keresés", Loading:"Betöltés…", Chat:"Csevegés", Dashboard:"Irányítópult", Progress:"Haladás", Analytics:"Elemzés", Capabilities:"Képességek", About:"A Nováról", Send:"Küldés", New:"Új csevegés", Latest:"Ugrás a legfrissebbhez", Retry:"Újra", Regenerate:"Újragenerálás", Logout:"Kijelentkezés", Name:"Név", Level:"Tanulási szint", Teaching:"Tanítási stílus", Difficulty:"Nehézség", Length:"Válasz hossza", Tone:"Hangnem", Custom:"Egyéni utasítások", Welcome:"Üdvözlünk a Novában", LearnMore:"További információ", Adaptive:"Adaptív tutor", Personal:"Személyes tutor", Practice:"Gyakorló coach", Explain:"Magyarázd el", Quiz:"Kérdezz ki", Hint:"Adj egy tippet", Summarize:"Összefoglalás", Delete:"Törlés", Edit:"Szerkesztés", Copy:"Másolás", Download:"Letöltés", History:"Előzmények", Clear:"Törlés", Close:"Bezárás", Confirm:"Megerősítés", Continue:"Folytatás", Home:"Kezdőlap", Account:"Fiók", General:"Általános", Preferences:"Beállítások", Appearance:"Megjelenés", Theme:"Téma", Notifications:"Értesítések", Privacy:"Adatvédelem", Security:"Biztonság", Help:"Súgó", SignIn:"Bejelentkezés", SignUp:"Regisztráció", Email:"E-mail", Password:"Jelszó", Username:"Felhasználónév", WelcomeBack:"Üdv újra", CreateAccount:"Fiók létrehozása", NoConversations:"Még nincsenek beszélgetések", NewConversation:"Új beszélgetés", StartConversation:"Beszélgetés indítása", AskNova:"Kérdezd Novát bármiről…", SaveChanges:"Módosítások mentése", Unsaved:"Nem mentett módosítások", DifficultyEasy:"Könnyű", DifficultyMedium:"Közepes", DifficultyHard:"Nehéz", Short:"Rövid", Balanced:"Kiegyensúlyozott", Detailed:"Részletes", Friendly:"Barátságos", Formal:"Formális", Casual:"Közvetlen", Enable:"Engedélyezés", Disable:"Letiltás", Yes:"Igen", No:"Nem", On:"Be", Off:"Ki", Optional:"Opcionális", Required:"Kötelező", Next:"Következő", Previous:"Előző", Done:"Kész", TryAgain:"Próbáld újra", Error:"Hiba", Success:"Siker", Online:"Online", Offline:"Offline", LoadingData:"Adatok betöltése…", NoData:"Nincs elérhető adat", Overview:"Áttekintés", Statistics:"Statisztikák", Total:"Összesen", Today:"Ma", Week:"Ezen a héten", Month:"Ebben a hónapban", AllTime:"Minden időszak", LanguageDescription:"A nyelv, amelyet a Novának általában használnia kell.", AdaptiveDescription:"A magyarázatokat a szintedhez igazítja.", PersonalDescription:"Vezetett, lépésről lépésre segítség.", PracticeDescription:"Gyakorlatok, tippek és visszajelzés." },
  id: { Back:"Kembali", Settings:"Pengaturan", Profile:"Profil", Language:"Bahasa", Save:"Simpan perubahan", Saved:"Tersimpan", Cancel:"Batal", Reset:"Atur ulang", Search:"Cari", Loading:"Memuat…", Chat:"Obrolan", Dashboard:"Dasbor", Progress:"Kemajuan", Analytics:"Analitik", Capabilities:"Kemampuan", About:"Tentang Nova", Send:"Kirim", New:"Obrolan baru", Latest:"Ke yang terbaru", Retry:"Coba lagi", Regenerate:"Buat ulang", Logout:"Keluar", Name:"Nama", Level:"Tingkat belajar", Teaching:"Gaya mengajar", Difficulty:"Kesulitan", Length:"Panjang jawaban", Tone:"Nada", Custom:"Instruksi khusus", Welcome:"Selamat datang di Nova", LearnMore:"Pelajari lebih lanjut", Adaptive:"Tutor adaptif", Personal:"Tutor pribadi", Practice:"Pelatih latihan", Explain:"Jelaskan", Quiz:"Kuis saya", Hint:"Beri petunjuk", Summarize:"Ringkas", Delete:"Hapus", Edit:"Edit", Copy:"Salin", Download:"Unduh", History:"Riwayat", Clear:"Bersihkan", Close:"Tutup", Confirm:"Konfirmasi", Continue:"Lanjutkan", Home:"Beranda", Account:"Akun", General:"Umum", Preferences:"Preferensi", Appearance:"Tampilan", Theme:"Tema", Notifications:"Notifikasi", Privacy:"Privasi", Security:"Keamanan", Help:"Bantuan", SignIn:"Masuk", SignUp:"Daftar", Email:"Email", Password:"Kata sandi", Username:"Nama pengguna", WelcomeBack:"Selamat datang kembali", CreateAccount:"Buat akun", NoConversations:"Belum ada percakapan", NewConversation:"Percakapan baru", StartConversation:"Mulai percakapan", AskNova:"Tanyakan apa saja kepada Nova…", SaveChanges:"Simpan perubahan", Unsaved:"Perubahan belum disimpan", DifficultyEasy:"Mudah", DifficultyMedium:"Sedang", DifficultyHard:"Sulit", Short:"Singkat", Balanced:"Seimbang", Detailed:"Terperinci", Friendly:"Ramah", Formal:"Formal", Casual:"Santai", Enable:"Aktifkan", Disable:"Nonaktifkan", Yes:"Ya", No:"Tidak", On:"Aktif", Off:"Nonaktif", Optional:"Opsional", Required:"Wajib", Next:"Berikutnya", Previous:"Sebelumnya", Done:"Selesai", TryAgain:"Coba lagi", Error:"Kesalahan", Success:"Berhasil", Online:"Online", Offline:"Offline", LoadingData:"Memuat data…", NoData:"Tidak ada data", Overview:"Ringkasan", Statistics:"Statistik", Total:"Total", Today:"Hari ini", Week:"Minggu ini", Month:"Bulan ini", AllTime:"Sepanjang waktu", LanguageDescription:"Bahasa yang biasanya digunakan Nova.", AdaptiveDescription:"Menyesuaikan penjelasan dengan tingkatmu.", PersonalDescription:"Bantuan terpandu langkah demi langkah.", PracticeDescription:"Latihan, petunjuk, dan umpan balik." },
  vi: { Back:"Quay lại", Settings:"Cài đặt", Profile:"Hồ sơ", Language:"Ngôn ngữ", Save:"Lưu thay đổi", Saved:"Đã lưu", Cancel:"Hủy", Reset:"Đặt lại", Search:"Tìm kiếm", Loading:"Đang tải…", Chat:"Trò chuyện", Dashboard:"Bảng điều khiển", Progress:"Tiến độ", Analytics:"Phân tích", Capabilities:"Tính năng", About:"Về Nova", Send:"Gửi", New:"Cuộc trò chuyện mới", Latest:"Đến mới nhất", Retry:"Thử lại", Regenerate:"Tạo lại", Logout:"Đăng xuất", Name:"Tên", Level:"Trình độ học tập", Teaching:"Phong cách giảng dạy", Difficulty:"Độ khó", Length:"Độ dài câu trả lời", Tone:"Giọng điệu", Custom:"Hướng dẫn tùy chỉnh", Welcome:"Chào mừng đến với Nova", LearnMore:"Tìm hiểu thêm", Adaptive:"Gia sư thích ứng", Personal:"Gia sư cá nhân", Practice:"Huấn luyện thực hành", Explain:"Giải thích", Quiz:"Đố tôi", Hint:"Cho tôi gợi ý", Summarize:"Tóm tắt", Delete:"Xóa", Edit:"Chỉnh sửa", Copy:"Sao chép", Download:"Tải xuống", History:"Lịch sử", Clear:"Xóa sạch", Close:"Đóng", Confirm:"Xác nhận", Continue:"Tiếp tục", Home:"Trang chủ", Account:"Tài khoản", General:"Chung", Preferences:"Tùy chọn", Appearance:"Giao diện", Theme:"Chủ đề", Notifications:"Thông báo", Privacy:"Quyền riêng tư", Security:"Bảo mật", Help:"Trợ giúp", SignIn:"Đăng nhập", SignUp:"Đăng ký", Email:"Email", Password:"Mật khẩu", Username:"Tên người dùng", WelcomeBack:"Chào mừng trở lại", CreateAccount:"Tạo tài khoản", NoConversations:"Chưa có cuộc trò chuyện", NewConversation:"Cuộc trò chuyện mới", StartConversation:"Bắt đầu trò chuyện", AskNova:"Hỏi Nova bất cứ điều gì…", SaveChanges:"Lưu thay đổi", Unsaved:"Thay đổi chưa lưu", DifficultyEasy:"Dễ", DifficultyMedium:"Trung bình", DifficultyHard:"Khó", Short:"Ngắn", Balanced:"Cân bằng", Detailed:"Chi tiết", Friendly:"Thân thiện", Formal:"Trang trọng", Casual:"Thân mật", Enable:"Bật", Disable:"Tắt", Yes:"Có", No:"Không", On:"Bật", Off:"Tắt", Optional:"Tùy chọn", Required:"Bắt buộc", Next:"Tiếp theo", Previous:"Trước", Done:"Xong", TryAgain:"Thử lại", Error:"Lỗi", Success:"Thành công", Online:"Trực tuyến", Offline:"Ngoại tuyến", LoadingData:"Đang tải dữ liệu…", NoData:"Không có dữ liệu", Overview:"Tổng quan", Statistics:"Thống kê", Total:"Tổng", Today:"Hôm nay", Week:"Tuần này", Month:"Tháng này", AllTime:"Mọi thời gian", LanguageDescription:"Ngôn ngữ Nova thường sử dụng.", AdaptiveDescription:"Điều chỉnh giải thích theo trình độ của bạn.", PersonalDescription:"Hướng dẫn từng bước.", PracticeDescription:"Bài tập, gợi ý và phản hồi." },
  th: { Back:"ย้อนกลับ", Settings:"การตั้งค่า", Profile:"โปรไฟล์", Language:"ภาษา", Save:"บันทึกการเปลี่ยนแปลง", Saved:"บันทึกแล้ว", Cancel:"ยกเลิก", Reset:"รีเซ็ต", Search:"ค้นหา", Loading:"กำลังโหลด…", Chat:"แชต", Dashboard:"แดชบอร์ด", Progress:"ความคืบหน้า", Analytics:"การวิเคราะห์", Capabilities:"ความสามารถ", About:"เกี่ยวกับ Nova", Send:"ส่ง", New:"แชตใหม่", Latest:"ไปยังล่าสุด", Retry:"ลองอีกครั้ง", Regenerate:"สร้างใหม่", Logout:"ออกจากระบบ", Name:"ชื่อ", Level:"ระดับการเรียนรู้", Teaching:"รูปแบบการสอน", Difficulty:"ความยาก", Length:"ความยาวคำตอบ", Tone:"โทน", Custom:"คำสั่งกำหนดเอง", Welcome:"ยินดีต้อนรับสู่ Nova", LearnMore:"เรียนรู้เพิ่มเติม", Adaptive:"ติวเตอร์แบบปรับตัว", Personal:"ติวเตอร์ส่วนตัว", Practice:"โค้ชฝึกฝน", Explain:"อธิบาย", Quiz:"ถามฉัน", Hint:"ให้คำใบ้", Summarize:"สรุป", Delete:"ลบ", Edit:"แก้ไข", Copy:"คัดลอก", Download:"ดาวน์โหลด", History:"ประวัติ", Clear:"ล้าง", Close:"ปิด", Confirm:"ยืนยัน", Continue:"ดำเนินการต่อ", Home:"หน้าหลัก", Account:"บัญชี", General:"ทั่วไป", Preferences:"การตั้งค่า", Appearance:"รูปลักษณ์", Theme:"ธีม", Notifications:"การแจ้งเตือน", Privacy:"ความเป็นส่วนตัว", Security:"ความปลอดภัย", Help:"ช่วยเหลือ", SignIn:"เข้าสู่ระบบ", SignUp:"สมัครสมาชิก", Email:"อีเมล", Password:"รหัสผ่าน", Username:"ชื่อผู้ใช้", WelcomeBack:"ยินดีต้อนรับกลับ", CreateAccount:"สร้างบัญชี", NoConversations:"ยังไม่มีการสนทนา", NewConversation:"การสนทนาใหม่", StartConversation:"เริ่มการสนทนา", AskNova:"ถาม Nova ได้ทุกเรื่อง…", SaveChanges:"บันทึกการเปลี่ยนแปลง", Unsaved:"มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก", DifficultyEasy:"ง่าย", DifficultyMedium:"ปานกลาง", DifficultyHard:"ยาก", Short:"สั้น", Balanced:"สมดุล", Detailed:"ละเอียด", Friendly:"เป็นมิตร", Formal:"เป็นทางการ", Casual:"ไม่เป็นทางการ", Enable:"เปิดใช้งาน", Disable:"ปิดใช้งาน", Yes:"ใช่", No:"ไม่", On:"เปิด", Off:"ปิด", Optional:"ไม่บังคับ", Required:"จำเป็น", Next:"ถัดไป", Previous:"ก่อนหน้า", Done:"เสร็จสิ้น", TryAgain:"ลองอีกครั้ง", Error:"ข้อผิดพลาด", Success:"สำเร็จ", Online:"ออนไลน์", Offline:"ออฟไลน์", LoadingData:"กำลังโหลดข้อมูล…", NoData:"ไม่มีข้อมูล", Overview:"ภาพรวม", Statistics:"สถิติ", Total:"ทั้งหมด", Today:"วันนี้", Week:"สัปดาห์นี้", Month:"เดือนนี้", AllTime:"ทั้งหมด", LanguageDescription:"ภาษาที่ Nova ควรใช้เป็นหลัก", AdaptiveDescription:"ปรับคำอธิบายตามระดับของคุณ", PersonalDescription:"ความช่วยเหลือแบบทีละขั้นตอน", PracticeDescription:"แบบฝึกหัด คำใบ้ และข้อเสนอแนะ" },
  ar: { Back:"رجوع", Settings:"الإعدادات", Profile:"الملف الشخصي", Language:"اللغة", Save:"حفظ التغييرات", Saved:"تم الحفظ", Cancel:"إلغاء", Reset:"إعادة تعيين", Search:"بحث", Loading:"جارٍ التحميل…", Chat:"الدردشة", Dashboard:"لوحة التحكم", Progress:"التقدم", Analytics:"التحليلات", Capabilities:"القدرات", About:"حول Nova", Send:"إرسال", New:"محادثة جديدة", Latest:"الانتقال إلى الأحدث", Retry:"إعادة المحاولة", Regenerate:"إعادة الإنشاء", Logout:"تسجيل الخروج", Name:"الاسم", Level:"مستوى التعلم", Teaching:"أسلوب التدريس", Difficulty:"الصعوبة", Length:"طول الإجابة", Tone:"النبرة", Custom:"تعليمات مخصصة", Welcome:"مرحبًا بك في Nova", LearnMore:"معرفة المزيد", Adaptive:"مدرس متكيف", Personal:"مدرس شخصي", Practice:"مدرب تدريب", Explain:"شرح", Quiz:"اختبرني", Hint:"أعطني تلميحًا", Summarize:"تلخيص", Delete:"حذف", Edit:"تعديل", Copy:"نسخ", Download:"تنزيل", History:"السجل", Clear:"مسح", Close:"إغلاق", Confirm:"تأكيد", Continue:"متابعة", Home:"الرئيسية", Account:"الحساب", General:"عام", Preferences:"التفضيلات", Appearance:"المظهر", Theme:"السمة", Notifications:"الإشعارات", Privacy:"الخصوصية", Security:"الأمان", Help:"المساعدة", SignIn:"تسجيل الدخول", SignUp:"إنشاء حساب", Email:"البريد الإلكتروني", Password:"كلمة المرور", Username:"اسم المستخدم", WelcomeBack:"مرحبًا بعودتك", CreateAccount:"إنشاء حساب", NoConversations:"لا توجد محادثات بعد", NewConversation:"محادثة جديدة", StartConversation:"بدء محادثة", AskNova:"اسأل Nova عن أي شيء…", SaveChanges:"حفظ التغييرات", Unsaved:"تغييرات غير محفوظة", DifficultyEasy:"سهل", DifficultyMedium:"متوسط", DifficultyHard:"صعب", Short:"قصير", Balanced:"متوازن", Detailed:"مفصل", Friendly:"ودود", Formal:"رسمي", Casual:"غير رسمي", Enable:"تفعيل", Disable:"تعطيل", Yes:"نعم", No:"لا", On:"مفعّل", Off:"متوقف", Optional:"اختياري", Required:"مطلوب", Next:"التالي", Previous:"السابق", Done:"تم", TryAgain:"حاول مرة أخرى", Error:"خطأ", Success:"نجاح", Online:"متصل", Offline:"غير متصل", LoadingData:"جارٍ تحميل البيانات…", NoData:"لا توجد بيانات متاحة", Overview:"نظرة عامة", Statistics:"الإحصائيات", Total:"الإجمالي", Today:"اليوم", Week:"هذا الأسبوع", Month:"هذا الشهر", AllTime:"كل الوقت", LanguageDescription:"اللغة التي ينبغي أن تستخدمها Nova عادةً.", AdaptiveDescription:"تكيّف الشروحات مع مستواك.", PersonalDescription:"مساعدة موجهة خطوة بخطوة.", PracticeDescription:"تمارين وتلميحات وملاحظات." },
  hi: { Back:"वापस", Settings:"सेटिंग्स", Profile:"प्रोफ़ाइल", Language:"भाषा", Save:"बदलाव सहेजें", Saved:"सहेजा गया", Cancel:"रद्द करें", Reset:"रीसेट", Search:"खोजें", Loading:"लोड हो रहा है…", Chat:"चैट", Dashboard:"डैशबोर्ड", Progress:"प्रगति", Analytics:"विश्लेषण", Capabilities:"सुविधाएँ", About:"Nova के बारे में", Send:"भेजें", New:"नई चैट", Latest:"नवीनतम पर जाएँ", Retry:"फिर कोशिश करें", Regenerate:"फिर से बनाएँ", Logout:"लॉग आउट", Name:"नाम", Level:"सीखने का स्तर", Teaching:"शिक्षण शैली", Difficulty:"कठिनाई", Length:"उत्तर की लंबाई", Tone:"टोन", Custom:"कस्टम निर्देश", Welcome:"Nova में आपका स्वागत है", LearnMore:"और जानें", Adaptive:"अनुकूली ट्यूटर", Personal:"व्यक्तिगत ट्यूटर", Practice:"अभ्यास कोच", Explain:"समझाएँ", Quiz:"मुझसे क्विज़ लें", Hint:"संकेत दें", Summarize:"सारांश दें", Delete:"हटाएँ", Edit:"संपादित करें", Copy:"कॉपी करें", Download:"डाउनलोड करें", History:"इतिहास", Clear:"साफ़ करें", Close:"बंद करें", Confirm:"पुष्टि करें", Continue:"जारी रखें", Home:"होम", Account:"खाता", General:"सामान्य", Preferences:"प्राथमिकताएँ", Appearance:"दिखावट", Theme:"थीम", Notifications:"सूचनाएँ", Privacy:"गोपनीयता", Security:"सुरक्षा", Help:"मदद", SignIn:"साइन इन", SignUp:"साइन अप", Email:"ईमेल", Password:"पासवर्ड", Username:"उपयोगकर्ता नाम", WelcomeBack:"वापसी पर स्वागत है", CreateAccount:"खाता बनाएँ", NoConversations:"अभी कोई बातचीत नहीं", NewConversation:"नई बातचीत", StartConversation:"बातचीत शुरू करें", AskNova:"Nova से कुछ भी पूछें…", SaveChanges:"बदलाव सहेजें", Unsaved:"सहेजे न गए बदलाव", DifficultyEasy:"आसान", DifficultyMedium:"मध्यम", DifficultyHard:"कठिन", Short:"छोटा", Balanced:"संतुलित", Detailed:"विस्तृत", Friendly:"दोस्ताना", Formal:"औपचारिक", Casual:"अनौपचारिक", Enable:"सक्षम करें", Disable:"अक्षम करें", Yes:"हाँ", No:"नहीं", On:"चालू", Off:"बंद", Optional:"वैकल्पिक", Required:"आवश्यक", Next:"अगला", Previous:"पिछला", Done:"हो गया", TryAgain:"फिर कोशिश करें", Error:"त्रुटि", Success:"सफल", Online:"ऑनलाइन", Offline:"ऑफ़लाइन", LoadingData:"डेटा लोड हो रहा है…", NoData:"कोई डेटा उपलब्ध नहीं", Overview:"अवलोकन", Statistics:"आँकड़े", Total:"कुल", Today:"आज", Week:"इस सप्ताह", Month:"इस महीने", AllTime:"सभी समय", LanguageDescription:"वह भाषा जिसे Nova सामान्यतः उपयोग करे।", AdaptiveDescription:"व्याख्याओं को आपके स्तर के अनुसार ढालता है।", PersonalDescription:"चरण-दर-चरण मार्गदर्शित सहायता।", PracticeDescription:"अभ्यास, संकेत और प्रतिक्रिया।" },
  ko: { Back:"뒤로", Settings:"설정", Profile:"프로필", Language:"언어", Save:"변경 사항 저장", Saved:"저장됨", Cancel:"취소", Reset:"재설정", Search:"검색", Loading:"로드 중…", Chat:"채팅", Dashboard:"대시보드", Progress:"진행 상황", Analytics:"분석", Capabilities:"기능", About:"Nova 정보", Send:"보내기", New:"새 채팅", Latest:"최신으로 이동", Retry:"다시 시도", Regenerate:"다시 생성", Logout:"로그아웃", Name:"이름", Level:"학습 수준", Teaching:"학습 방식", Difficulty:"난이도", Length:"응답 길이", Tone:"말투", Custom:"사용자 지정 지침", Welcome:"Nova에 오신 것을 환영합니다", LearnMore:"자세히 보기", Adaptive:"적응형 튜터", Personal:"개인 튜터", Practice:"연습 코치", Explain:"설명", Quiz:"퀴즈 내기", Hint:"힌트 주기", Summarize:"요약", Delete:"삭제", Edit:"편집", Copy:"복사", Download:"다운로드", History:"기록", Clear:"지우기", Close:"닫기", Confirm:"확인", Continue:"계속", Home:"홈", Account:"계정", General:"일반", Preferences:"환경설정", Appearance:"모양", Theme:"테마", Notifications:"알림", Privacy:"개인정보 보호", Security:"보안", Help:"도움말", SignIn:"로그인", SignUp:"가입", Email:"이메일", Password:"비밀번호", Username:"사용자 이름", WelcomeBack:"다시 오신 것을 환영합니다", CreateAccount:"계정 만들기", NoConversations:"아직 대화가 없습니다", NewConversation:"새 대화", StartConversation:"대화 시작", AskNova:"Nova에게 무엇이든 물어보세요…", SaveChanges:"변경 사항 저장", Unsaved:"저장하지 않은 변경 사항", DifficultyEasy:"쉬움", DifficultyMedium:"보통", DifficultyHard:"어려움", Short:"짧게", Balanced:"균형", Detailed:"자세히", Friendly:"친근하게", Formal:"격식 있게", Casual:"편하게", Enable:"사용", Disable:"사용 안 함", Yes:"예", No:"아니요", On:"켜짐", Off:"꺼짐", Optional:"선택 사항", Required:"필수", Next:"다음", Previous:"이전", Done:"완료", TryAgain:"다시 시도", Error:"오류", Success:"성공", Online:"온라인", Offline:"오프라인", LoadingData:"데이터 로드 중…", NoData:"사용 가능한 데이터가 없습니다", Overview:"개요", Statistics:"통계", Total:"전체", Today:"오늘", Week:"이번 주", Month:"이번 달", AllTime:"전체 기간", LanguageDescription:"Nova가 일반적으로 사용할 언어입니다.", AdaptiveDescription:"설명을 학습 수준에 맞게 조정합니다.", PersonalDescription:"단계별 안내 도움말.", PracticeDescription:"연습, 힌트 및 피드백." },
  ja: { Back:"戻る", Settings:"設定", Profile:"プロフィール", Language:"言語", Save:"変更を保存", Saved:"保存しました", Cancel:"キャンセル", Reset:"リセット", Search:"検索", Loading:"読み込み中…", Chat:"チャット", Dashboard:"ダッシュボード", Progress:"進捗", Analytics:"分析", Capabilities:"機能", About:"Novaについて", Send:"送信", New:"新しいチャット", Latest:"最新へ", Retry:"再試行", Regenerate:"再生成", Logout:"ログアウト", Name:"名前", Level:"学習レベル", Teaching:"指導スタイル", Difficulty:"難易度", Length:"回答の長さ", Tone:"トーン", Custom:"カスタム指示", Welcome:"Novaへようこそ", LearnMore:"詳しく見る", Adaptive:"適応型チューター", Personal:"パーソナルチューター", Practice:"練習コーチ", Explain:"説明する", Quiz:"クイズを出す", Hint:"ヒントを出す", Summarize:"要約", Delete:"削除", Edit:"編集", Copy:"コピー", Download:"ダウンロード", History:"履歴", Clear:"クリア", Close:"閉じる", Confirm:"確認", Continue:"続ける", Home:"ホーム", Account:"アカウント", General:"一般", Preferences:"環境設定", Appearance:"外観", Theme:"テーマ", Notifications:"通知", Privacy:"プライバシー", Security:"セキュリティ", Help:"ヘルプ", SignIn:"ログイン", SignUp:"登録", Email:"メール", Password:"パスワード", Username:"ユーザー名", WelcomeBack:"おかえりなさい", CreateAccount:"アカウントを作成", NoConversations:"まだ会話はありません", NewConversation:"新しい会話", StartConversation:"会話を開始", AskNova:"Novaに何でも質問…", SaveChanges:"変更を保存", Unsaved:"未保存の変更", DifficultyEasy:"簡単", DifficultyMedium:"普通", DifficultyHard:"難しい", Short:"短い", Balanced:"バランス", Detailed:"詳細", Friendly:"フレンドリー", Formal:"フォーマル", Casual:"カジュアル", Enable:"有効", Disable:"無効", Yes:"はい", No:"いいえ", On:"オン", Off:"オフ", Optional:"任意", Required:"必須", Next:"次へ", Previous:"前へ", Done:"完了", TryAgain:"もう一度試す", Error:"エラー", Success:"成功", Online:"オンライン", Offline:"オフライン", LoadingData:"データを読み込み中…", NoData:"利用可能なデータはありません", Overview:"概要", Statistics:"統計", Total:"合計", Today:"今日", Week:"今週", Month:"今月", AllTime:"全期間", LanguageDescription:"Novaが通常使用する言語です。", AdaptiveDescription:"説明をあなたのレベルに合わせます。", PersonalDescription:"ステップごとのガイド付きサポート。", PracticeDescription:"練習、ヒント、フィードバック。" },
  zh: { Back:"返回", Settings:"设置", Profile:"个人资料", Language:"语言", Save:"保存更改", Saved:"已保存", Cancel:"取消", Reset:"重置", Search:"搜索", Loading:"加载中…", Chat:"聊天", Dashboard:"控制面板", Progress:"进度", Analytics:"分析", Capabilities:"功能", About:"关于 Nova", Send:"发送", New:"新对话", Latest:"跳到最新", Retry:"重试", Regenerate:"重新生成", Logout:"退出登录", Name:"姓名", Level:"学习水平", Teaching:"教学风格", Difficulty:"难度", Length:"回答长度", Tone:"语气", Custom:"自定义指令", Welcome:"欢迎使用 Nova", LearnMore:"了解更多", Adaptive:"自适应导师", Personal:"私人导师", Practice:"练习教练", Explain:"解释", Quiz:"测试我", Hint:"给我提示", Summarize:"总结", Delete:"删除", Edit:"编辑", Copy:"复制", Download:"下载", History:"历史记录", Clear:"清除", Close:"关闭", Confirm:"确认", Continue:"继续", Home:"主页", Account:"账户", General:"常规", Preferences:"偏好设置", Appearance:"外观", Theme:"主题", Notifications:"通知", Privacy:"隐私", Security:"安全", Help:"帮助", SignIn:"登录", SignUp:"注册", Email:"电子邮件", Password:"密码", Username:"用户名", WelcomeBack:"欢迎回来", CreateAccount:"创建账户", NoConversations:"还没有对话", NewConversation:"新对话", StartConversation:"开始对话", AskNova:"向 Nova 询问任何问题…", SaveChanges:"保存更改", Unsaved:"未保存的更改", DifficultyEasy:"简单", DifficultyMedium:"中等", DifficultyHard:"困难", Short:"简短", Balanced:"平衡", Detailed:"详细", Friendly:"友好", Formal:"正式", Casual:"随意", Enable:"启用", Disable:"禁用", Yes:"是", No:"否", On:"开启", Off:"关闭", Optional:"可选", Required:"必填", Next:"下一步", Previous:"上一步", Done:"完成", TryAgain:"重试", Error:"错误", Success:"成功", Online:"在线", Offline:"离线", LoadingData:"正在加载数据…", NoData:"没有可用数据", Overview:"概览", Statistics:"统计", Total:"总计", Today:"今天", Week:"本周", Month:"本月", AllTime:"全部时间", LanguageDescription:"Nova通常使用的语言。", AdaptiveDescription:"根据你的水平调整解释。", PersonalDescription:"分步骤引导帮助。", PracticeDescription:"练习、提示和反馈。" }
};

const WORD_ALIASES = {
  en:["back","settings","profile","language","save","saved","cancel","reset","search","loading","chat","dashboard","progress","analytics","capabilities","about","send","new","latest","retry","regenerate","logout","name","level","teaching","difficulty","length","tone","custom","welcome","learn","adaptive","personal","practice","explain","quiz","hint","summarize","delete","edit","copy","download","history","clear","close","confirm","continue","home","account","general","preferences","appearance","theme","notifications","privacy","security","help","sign","email","password","username","conversation","start","question","answer","easy","medium","hard","short","balanced","detailed","friendly","formal","casual","enable","disable","yes","no","online","offline","overview","statistics","total","today","week","month","optional","required","next","previous","done","error","success"],
  fr:["retour","paramètres","profil","langue","enregistrer","annuler","réinitialiser","rechercher","chargement","discussion","tableau","progression","analyses","fonctionnalités","à propos","envoyer","nouvelle","dernier","réessayer","régénérer","déconnecter","nom","niveau","enseignement","difficulté","longueur","ton","instructions","bienvenue","apprendre","adaptatif","personnel","pratique","expliquer","quiz","indice","résumer","supprimer","modifier","copier","télécharger","historique","effacer","fermer","confirmer","continuer","accueil","compte","général","préférences","apparence","thème","notifications","confidentialité","sécurité","aide","connexion","email","mot","passe","utilisateur","conversation","commencer","question","réponse","facile","moyen","difficile","court","équilibré","détaillé","amical","formel","décontracté","activer","désactiver","oui","non","ligne","hors","aperçu","statistiques","total","aujourd’hui","semaine","mois","facultatif","obligatoire","suivant","précédent","terminé","erreur","réussi"]
};

function sourceKey(text) {
  const normalized = text.replace(/\s+/g, " ").trim();
  for (const [key, value] of Object.entries(UI.en)) {
    if (value === normalized) return key;
  }
  return null;
}

function shouldSkipElement(element) {
  if (!element || element.nodeType !== 1) return true;
  if (element.closest("pre, code, textarea, input, [contenteditable=\"true\"], .prose, [data-nova-no-translate]")) return true;
  if (element.closest("select")) return true;
  const cls = String(element.className || "").toLowerCase();
  if (/message|markdown|assistant-response|user-message/.test(cls)) return true;
  return false;
}

function translateText(text, language) {
  const clean = text.replace(/\s+/g, " ").trim();
  if (!clean || language.code === "en") return text;
  const dictionary = UI[language.code] || UI.en;
  const key = sourceKey(clean);
  if (key && dictionary[key]) return text.replace(clean, dictionary[key]);

  /* Phrase aliases used heavily by the chat and settings pages. */
  const phrases = [
    ["Adaptive Tutor", "Adaptive"], ["Personal Tutor", "Personal"], ["Practice Coach", "Practice"],
    ["Explain a difficult concept", "Explain"], ["Help me study", "StartConversation"], ["Quiz me", "Quiz"],
    ["Give me a hint", "Hint"], ["Summarize", "Summarize"], ["Save changes", "SaveChanges"],
    ["The language Nova should normally use.", "LanguageDescription"],
    ["Adjusts explanations to your level.", "AdaptiveDescription"],
    ["Guided, step-by-step help.", "PersonalDescription"],
    ["Exercises, hints and feedback.", "PracticeDescription"],
    ["Welcome to Nova", "Welcome"], ["Welcome back", "WelcomeBack"],
    ["Create account", "CreateAccount"], ["No conversations yet", "NoConversations"],
    ["New conversation", "NewConversation"], ["Start a conversation", "StartConversation"],
    ["Ask Nova anything…", "AskNova"], ["Ask Nova anything...", "AskNova"]
  ];
  for (const [english, dictKey] of phrases) {
    if (clean.toLowerCase() === english.toLowerCase() && dictionary[dictKey]) return text.replace(clean, dictionary[dictKey]);
  }
  return text;
}

function translateDocument() {
  const language = normalizeLanguage(readNovaLanguage());
  applyNovaLanguage(language.code);
  if (!document.body) return;

  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    const element = node.parentElement;
    if (!element || shouldSkipElement(element)) continue;
    if (!node.__novaSource) node.__novaSource = node.nodeValue;
    const translated = translateText(node.__novaSource, language);
    if (translated !== node.nodeValue) node.nodeValue = translated;
  }

  for (const element of document.querySelectorAll("[title], [aria-label], [placeholder]")) {
    if (shouldSkipElement(element)) continue;
    if (!element.__novaAttrs) element.__novaAttrs = {};
    for (const attribute of ["title", "aria-label", "placeholder"]) {
      if (!element.hasAttribute(attribute)) continue;
      if (element.__novaAttrs[attribute] === undefined) element.__novaAttrs[attribute] = element.getAttribute(attribute);
      const original = element.__novaAttrs[attribute];
      const translated = translateText(original, language);
      if (translated) element.setAttribute(attribute, translated);
    }
  }
}

let observerStarted = false;
let scheduled = false;
function scheduleTranslation() {
  if (scheduled) return;
  scheduled = true;
  requestAnimationFrame(() => {
    scheduled = false;
    translateDocument();
  });
}

function start() {
  translateDocument();
  if (observerStarted || !document.body) return;
  observerStarted = true;
  const observer = new MutationObserver(scheduleTranslation);
  observer.observe(document.body, { childList: true, subtree: true });
  window.addEventListener("nova-language-changed", scheduleTranslation);
  window.addEventListener("storage", event => {
    if (event.key === "nova_language") scheduleTranslation();
  });
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", start, { once: true });
} else {
  start();
}
